### ISSUE TITLE
Traning crashes if Learning rate [and/or batchsize] changes

### ISSUE THREAD

**Issue by AminDar** [DLR-RM/stable-baselines3#1130]
### 🐛 Bug

I'm trying to train my custom gym using Stable-Baselines3. The environment has to deal with hourly changes in energy demand and act based on the best possible solution.
The training with default SAC hyper-parameters works fine. Although it doesn't perform well at all with other algorithms.

But changing SAC learning rate or batch size crashes the training.

Expected behavior:
changing different learning rate [or batch size] than default value shouldn't cause any major error in the training process

Actual behavior: 
Training crashes with NAN output of distribution  (see the Relevant log output / Error message section)

**Env Checker**
the env checker gives me [almost] no error.
 
```
 UserWarning: We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) cf https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html
  warnings.warn(

Process finished with exit code 0

```
I know that action space should be ranged symmetric but I'm not sure if it's causing my problem or not. since as I said the results seem fine with the default parameters and non-symmetric action space.

### Code example

```python
import gym
import numpy as np

from stable_baselines3 import SAC
from stable_baselines3.common.env_checker import check_env


class CustomEnv(gym.Env):

 def __init__(self, co_factor, fuel_factor):
    super().__init__()
    elf.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(10,), dtype=np.float32)
    self.action_space = spaces.Box(
            low=0.0, high=1.0, shape=(2,), dtype=np.float32
        )

  def reset(self):
    return self.observation_space.sample()

    def step(self, action: np.ndarray):

        if self.time_step % self.step_size == 0:
            hour_of_year = self.load_data.time[self.time_step]
            self.T_out = self.load_data.T_out[hour_of_year]
            self.demand = self.load_data.demand[hour_of_year]

        self.time_step += 1

        self.eff_1, self.eff_2, self.gen_heat_1, self.gen_heat_2, \
        self.co2_gen_1, self.co2_gen_2, self.fuel_price_1, self.fuel_price_2, T_out = boiler_eff(action[0], action[1],
                                                                                                 self.T_out)

        self.observation[0] = self.eff_1
        self.observation[1] = self.cop
        self.observation[2] = self.gen_heat_1
        self.observation[3] = self.gen_heat_2
        self.observation[4] = self.co2_gen_1
        self.observation[5] = self.co2_gen_2
        self.observation[6] = self.fuel_price_1
        self.observation[7] = self.fuel_price_2
        self.observation[8] = self.demand
        self.observation[9] = self.T_out

        reward = self._reward_compute(action[0], action[1], self.demand, self.T_out)

        info = {}

        # Update step number and check to see if epoch is over
        self.iter += 1

        if self.iter >= self.STEP_Limit:
            done = True
        else:
            done = False

        return self.observation, reward, done, info


```

> policy_kwargs = dict(net_arch=dict(pi=[256, 256], qf=[128, 128]))

> model = SAC("MlpPolicy", env, verbose=1, policy_kwargs=policy_kwargs, tensorboard_log="./Emstensorboard/",
>             learning_rate=lr)

> model.learn(total_timesteps=int(4e6), log_interval=50, callback=callback)

### Relevant log output / Error message

```shell
Using cuda device
Wrapping the env in a DummyVecEnv.
Logging to ./Emstensorboard/SAC_25
Traceback (most recent call last):
  File "/home/****//****//Private//****/ /****///****//Run/runStable_1.py", line 128, in <module>
    model.learn(total_timesteps=int(4e6), log_interval=50, callback=callback)
  File "/home/****/anaconda3/envs/stablebase/lib/python3.9/site-packages/stable_baselines3/sac/sac.py", line 298, in learn
    return super().learn(
  File "/"/home/****//****//Private//****/ /****///**/anaconda3/envs/stablebase/lib/python3.9/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 344, in learn
    rollout = self.collect_rollouts(
  File "/home/****//****///anaconda3/envs/stablebase/lib/python3.9/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 574, in collect_rollouts
    actions, buffer_actions = self._sample_action(learning_starts, action_noise, env.num_envs)
  File "/home/***/anaconda3/envs/stablebase/lib/python3.9/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 405, in _sample_action
    unscaled_action, _ = self.predict(self._last_obs, deterministic=False)
  File "/home/***/anaconda3/envs/stablebase/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 579, in predict
    return self.policy.predict(observation, state, episode_start, deterministic)
  File "/home/**/anaconda3/envs/stablebase/lib/python3.9/site-packages/stable_baselines3/common/policies.py", line 338, in predict
    actions = self._predict(observation, deterministic=deterministic)
  File "/home/**/anaconda3/envs/stablebase/lib/python3.9/site-packages/stable_baselines3/sac/policies.py", line 359, in _predict
    return self.actor(observation, deterministic)
  File "/home/**/anaconda3/envs/stablebase/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/***/anaconda3/envs/stablebase/lib/python3.9/site-packages/stable_baselines3/sac/policies.py", line 177, in forward
    return self.action_dist.actions_from_params(mean_actions, log_std, deterministic=deterministic, **kwargs)
  File "/home/**/anaconda3/envs/stablebase/lib/python3.9/site-packages/stable_baselines3/common/distributions.py", line 178, in actions_from_params
    self.proba_distribution(mean_actions, log_std)
  File "/home/***/anaconda3/envs/stablebase/lib/python3.9/site-packages/stable_baselines3/common/distributions.py", line 210, in proba_distribution
    super().proba_distribution(mean_actions, log_std)
  File "/home/**/anaconda3/envs/stablebase/lib/python3.9/site-packages/stable_baselines3/common/distributions.py", line 152, in proba_distribution
    self.distribution = Normal(mean_actions, action_std)
  File "/home/***/anaconda3/envs/stablebase/lib/python3.9/site-packages/torch/distributions/normal.py", line 50, in __init__
    super(Normal, self).__init__(batch_shape, validate_args=validate_args)
  File "/home/***/anaconda3/envs/stablebase/lib/python3.9/site-packages/torch/distributions/distribution.py", line 55, in __init__
    raise ValueError(
ValueError: Expected parameter loc (Tensor of shape (1, 2)) of distribution Normal(loc: torch.Size([1, 2]), scale: torch.Size([1, 2])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan]], device='cuda:0')

Process finished with exit code 1
```

### System Info

OS: Linux-5.15.0-50-generic-x86_64-with-glibc2.3
Python: 3.9.7
Stable-Baselines3: 1.5.1a8
PyTorch: 1.11.0
GPU Enabled: True
Numpy: 1.19.5
Gym: 0.21.0

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
>  changing different learning rate [or batch size] than default value shouldn't cause any major error in the training process
>  Training crashes with NAN output of distribution (see the Relevant log output / Error message section)

Probably related to https://github.com/DLR-RM/rl-baselines3-zoo/issues/156#issuecomment-910097343

I guess you are trying with higher learning rates and smaller batch size?

You should also check that your input data is normalized.

**Comment by AminDar** [comment]
I tried lr = 3e-2 and 3e-3 with the same batch size [256] but it didn't work.
I believe not all the inputs are normalized.

**Comment by araffin** [comment]
> I tried lr = 3e-2 and 3e-3 with the same batch size [256] but it didn't work.

That's pretty high learning rate compared to the default one (10x higher!), not a big surprise that you get NaNs...
so as a rule of thumb, you should normally increase the batch size if you increase the learning rate (in your case increase to 1024/2048 for instance)

**Comment by jiangzhangze** [comment]
Hi @araffin ，I met this error too with the lr=1e-7 and the batch_size=256.(I have reudced lr two times but it didn't work！).Should I reduce lr once more or increase the batch_size？
