### ISSUE TITLE
[Question] questionTypeError: float() argument must be a string or a number, not 'dict' title

### ISSUE THREAD

**Issue by shile1998** [DLR-RM/stable-baselines3#1357]
### ❓ Question

python=3.6
stable-baselines3=1.3.0

`env = gym.make('carla-v0', params=params)
print(env.observation_space)
model = SAC('MlpPolicy', env, verbose=1)
model.learn(total_timesteps=int(200))
model.save("sac_cartpole")
del model`

Box([-2. -1. -5.  0.], [ 2.  1. 30.  1.], (4,), float32)
Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Traceback (most recent call last):
  File "tes.py", line 70, in <module>
    model.learn(total_timesteps=int(200))
  File "/home/sl/.conda/envs/ca/lib/python3.6/site-packages/stable_baselines3/sac/sac.py", line 300, in learn
    reset_num_timesteps=reset_num_timesteps,
  File "/home/sl/.conda/envs/ca/lib/python3.6/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 346, in learn
    tb_log_name,
  File "/home/sl/.conda/envs/ca/lib/python3.6/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 322, in _setup_learn
    tb_log_name,
  File "/home/sl/.conda/envs/ca/lib/python3.6/site-packages/stable_baselines3/common/base_class.py", line 421, in _setup_learn
    self._last_obs = self.env.reset()  # pytype: disable=annotation-type-mismatch
  File "/home/sl/.conda/envs/ca/lib/python3.6/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 62, in reset
    self._save_obs(env_idx, obs)
  File "/home/sl/.conda/envs/ca/lib/python3.6/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 92, in _save_obs
    self.buf_obs[key][env_idx] = obs
TypeError: float() argument must be a string or a number, not 'dict'

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
please fill in the custom env template completely.

> If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

Please follow that requirement too (format your code and traceback using markdown code block.
