### ISSUE TITLE
[Bug]:  kwarg action_repeat_probability for AtariWrapper missing on pypi distribution

### ISSUE THREAD

**Issue by KandBM** [DLR-RM/stable-baselines3#1410]
### 🐛 Bug

Despite being in the sb3 documentation and linked source code, the kwarg action_repeat_probability is missing from the AtariWrapper method in atari_wrapper.py in my environment. I intalled the package in a conda environment using pip.

### To Reproduce

```python
rom stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.env_util import make_atari_env

env_id = "BreakoutNoFrameskip-v4"
n_actors = 10 # authors used 8 actors, should w change n_steps?
SEED = 42
atari_wrapper_kwargs = dict(
    frame_skip=4, #don't use 0
    screen_size=84,
    action_repeat_probability=0.1 
)

env = make_atari_env(env_id, n_envs=n_actors, seed=SEED,vec_env_cls=DummyVecEnv,wrapper_kwargs=atari_wrapper_kwargs)
env = VecFrameStack(env, n_stack=4)
```

### Relevant log output / Error message

```shell
A.L.E: Arcade Learning Environment (version 0.7.4+069f8bd)
[Powered by Stella]
Traceback (most recent call last):
  File "C:\Users\kbrod\OneDrive\Documents\RMC PGT\CISC 856\ppo_atari.py", line 21, in <module>
    env = make_atari_env(env_id, n_envs=n_actors, seed=SEED,vec_env_cls=DummyVecEnv,wrapper_kwargs=atari_wrapper_kwargs)
  File "C:\Users\kbrod\anaconda3\envs\stablebaselines\lib\site-packages\stable_baselines3\common\env_util.py", line 141, in make_atari_env
    return make_vec_env(
  File "C:\Users\kbrod\anaconda3\envs\stablebaselines\lib\site-packages\stable_baselines3\common\env_util.py", line 108, in make_vec_env
    return vec_env_cls([make_env(i + start_index) for i 
in range(n_envs)], **vec_env_kwargs)
  File "C:\Users\kbrod\anaconda3\envs\stablebaselines\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 26, in __init__
    self.envs = [fn() for fn in env_fns]
  File "C:\Users\kbrod\anaconda3\envs\stablebaselines\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 26, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "C:\Users\kbrod\anaconda3\envs\stablebaselines\lib\site-packages\stable_baselines3\common\env_util.py", line 98, in _init
    env = wrapper_class(env, **wrapper_kwargs)
TypeError: AtariWrapper.__init__() got an unexpected keyword argument 'action_repeat_probability'
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
you need SB3 master version for that (see documentation on how to install) or use `--pre` flag for pip to install beta version.
The documentation is always the one of master.

**Comment by KandBM** [comment]
Thanks, that makes sense. The difference wasn't clear from the docs
