### ISSUE TITLE
DDPG in SB3 not working

### ISSUE THREAD

**Issue by acq3047** [DLR-RM/stable-baselines3#1609]
### 🐛 Bug

I am reaching out to seek your assistance with an issue I am encountering while attempting to run my DDPG environment. Despite my best efforts, I am consistently encountering an error and am uncertain of the root cause.

As such, I would be incredibly grateful for any insights or guidance that you may be able to provide in order to help me resolve this issue. Your expertise and assistance would be greatly appreciated.

Thank you for your time and consideration.

### Code example

```python
#import gym
import gymnasium as gym
import numpy as np
import time
from typing import Optional
from reinforcement_learning.airgym.envs.car_env import AirSimCarEnv
from stable_baselines3 import DQN, DDPG
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.vec_env import DummyVecEnv, VecTransposeImage
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.noise import NormalActionNoise,OrnsteinUhlenbeckActionNoise
from stable_baselines3.common.callbacks import EvalCallback

# create the environment
env=gym.make("airgym:airsim-car-sample-v1", ip_address="127.0.0.4", image_shape=(84, 84, 1))
#n_actions = env.action_space.shape[-1]
# Initialize RL algorithm type and parameters
# NormalActionNoise(mean=np.zeros(n_actions), sigma=0.1 * np.ones(n_actions))
model = DDPG(
    "CnnPolicy",
    env,
    learning_rate=0.00025,
    verbose=1,
    batch_size=32,
    train_freq=(1, 'episode'),
    gamma=0.99,  # Discount factor
    learning_starts=200000,
    buffer_size=500000,
    tau=0.005,  # soft update coefficient
    gradient_steps=-1,
    optimize_memory_usage=False,
    seed=None,
    action_noise=None,
    replay_buffer_class=None,
    replay_buffer_kwargs=None,
    device="auto",
    tensorboard_log="./tb_logs/",
    _init_setup_model=True,
)

# Create an evaluation callback with the same env, called every 10000 iterations
callbacks = []
eval_callback = EvalCallback(
    env,
    callback_on_new_best=None,
    n_eval_episodes=5,
    best_model_save_path=".",
    log_path=".",
    eval_freq=10000,
)
callbacks.append(eval_callback)

kwargs = {}
kwargs["callback"] = callbacks

# Train for a certain number of timesteps
model.learn(
    total_timesteps=5e5, tb_log_name="ddpg_airsim_car_run_" + str(time.time()), **kwargs
)

# Save policy weights
model.save("ddpg_airsim_car_policy")
del model # remove to demonstrate saving and loading

model = DQN.load("ddpg_airsim_car_policy")

obs, info = env.reset()
while True:
    action, _states = model.predict(obs, deterministic=True)
    obs, reward, terminated, truncated, info = env.step(action)
    env.render()
    if terminated or truncated:
        obs, info = env.reset()

```

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "C:\Users\acq30\PycharmProjects\pythonProject3\reinforcemnt_learning2\ddpg_car.py", line 20, in <module>
    model = DDPG(
  File "C:\Users\acq30\OneDrive\Documents\Engineering Programming\pythonProject3\lib\site-packages\stable_baselines3\ddpg\ddpg.py", line 79, in __init__
    super().__init__(
  File "C:\Users\acq30\OneDrive\Documents\Engineering Programming\pythonProject3\lib\site-packages\stable_baselines3\td3\td3.py", line 106, in __init__
    super().__init__(
  File "C:\Users\acq30\OneDrive\Documents\Engineering Programming\pythonProject3\lib\site-packages\stable_baselines3\common\off_policy_algorithm.py", line 110, in __init__
    super().__init__(
  File "C:\Users\acq30\OneDrive\Documents\Engineering Programming\pythonProject3\lib\site-packages\stable_baselines3\common\base_class.py", line 180, in __init__
    assert isinstance(self.action_space, supported_action_spaces), (
AssertionError: The algorithm only supports (<class 'gymnasium.spaces.box.Box'>,) as action spaces but Discrete(6) was provided
```

### System Info

- Python version: 3.9
- PyTorch version: 2.0.1
- Gymnasium version: 0.28.1
- Gym version: 0.26.2

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by woipi90** [comment]
hm, are you trying to load a ddpg model as dqn?

**Comment by acq3047** [comment]
Hello @woipi90 , @araffin , @davidsblom , @cool-RR , I have noticed a typo error in the previously uploaded file. I apologize for any inconvenience this may have caused. I will now proceed to upload the correct version of the file. Thank you for your understanding.
```python
#import gym
import gymnasium as gym
import numpy as np
import time
from typing import Optional
from reinforcement_learning.airgym.envs.car_env import AirSimCarEnv
from stable_baselines3 import DQN, DDPG
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.vec_env import DummyVecEnv, VecTransposeImage
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.noise import NormalActionNoise,OrnsteinUhlenbeckActionNoise
from stable_baselines3.common.callbacks import EvalCallback

# create the environment
env=gym.make("airgym:airsim-car-sample-v0", ip_address="127.0.0.4", image_shape=(84, 84, 1))
#n_actions = env.action_space.shape[-1]
# Initialize RL algorithm type and parameters
# NormalActionNoise(mean=np.zeros(n_actions), sigma=0.1 * np.ones(n_actions))
model = DDPG(
    "CnnPolicy",
    env,
    learning_rate=0.00025,
    verbose=1,
    batch_size=32,
    train_freq=(1, 'episode'),
    gamma=0.99,  # Discount factor
    learning_starts=200000,
    buffer_size=500000,
    tau=0.005,  # soft update coefficient
    gradient_steps=-1,
    optimize_memory_usage=False,
    seed=None,
    action_noise=None,
    replay_buffer_class=None,
    replay_buffer_kwargs=None,
    device="auto",
    tensorboard_log="./tb_logs/",
    _init_setup_model=True,
)

# Create an evaluation callback with the same env, called every 10000 iterations
callbacks = []
eval_callback = EvalCallback(
    env,
    callback_on_new_best=None,
    n_eval_episodes=5,
    best_model_save_path=".",
    log_path=".",
    eval_freq=10000,
)
callbacks.append(eval_callback)

kwargs = {}
kwargs["callback"] = callbacks

# Train for a certain number of timesteps
model.learn(
    total_timesteps=5e5, tb_log_name="ddpg_airsim_car_run_" + str(time.time()), **kwargs
)

# Save policy weights
model.save("ddpg_airsim_car_policy")
del model # remove to demonstrate saving and loading

model = DDPG.load("ddpg_airsim_car_policy")

obs, info = env.reset()
while True:
    action, _states = model.predict(obs, deterministic=True)
    obs, reward, terminated, truncated, info = env.step(action)
    env.render()
    if terminated or truncated:
        obs, info = env.reset()
```
I am currently receiving an error message that reads as follows:

```Traceback (most recent call last):
  File "C:\Users\acq30\PycharmProjects\pythonProject3\reinforcemnt_learning2\ddpg2.py", line 57, in <module>
    model.learn(
  File "C:\Users\acq30\OneDrive\Documents\Engineering Programming\pythonProject3\lib\site-packages\stable_baselines3\ddpg\ddpg.py", line 123, in learn
    return super().learn(
  File "C:\Users\acq30\OneDrive\Documents\Engineering Programming\pythonProject3\lib\site-packages\stable_baselines3\td3\td3.py", line 222, in learn
    return super().learn(
  File "C:\Users\acq30\OneDrive\Documents\Engineering Programming\pythonProject3\lib\site-packages\stable_baselines3\common\off_policy_algorithm.py", line 301, in learn
    total_timesteps, callback = self._setup_learn(
  File "C:\Users\acq30\OneDrive\Documents\Engineering Programming\pythonProject3\lib\site-packages\stable_baselines3\common\off_policy_algorithm.py", line 284, in _setup_learn
    return super()._setup_learn(
  File "C:\Users\acq30\OneDrive\Documents\Engineering Programming\pythonProject3\lib\site-packages\stable_baselines3\common\base_class.py", line 424, in _setup_learn
    self._last_obs = self.env.reset()  # type: ignore[assignment]
  File "C:\Users\acq30\OneDrive\Documents\Engineering Programming\pythonProject3\lib\site-packages\stable_baselines3\common\vec_env\vec_transpose.py", line 110, in reset
    return self.transpose_observations(self.venv.reset())
  File "C:\Users\acq30\OneDrive\Documents\Engineering Programming\pythonProject3\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 76, in reset
    obs, self.reset_infos[env_idx] = self.envs[env_idx].reset(seed=self._seeds[env_idx])
  File "C:\Users\acq30\OneDrive\Documents\Engineering Programming\pythonProject3\lib\site-packages\stable_baselines3\common\monitor.py", line 83, in reset
    return self.env.reset(**kwargs)
  File "C:\Users\acq30\OneDrive\Documents\Engineering Programming\pythonProject3\lib\site-packages\gymnasium\wrappers\order_enforcing.py", line 61, in reset
    return self.env.reset(**kwargs)
  File "C:\Users\acq30\OneDrive\Documents\Engineering Programming\pythonProject3\lib\site-packages\gymnasium\wrappers\env_checker.py", line 55, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "C:\Users\acq30\OneDrive\Documents\Engineering Programming\pythonProject3\lib\site-packages\gymnasium\utils\passive_env_checker.py", line 215, in env_reset_passive_checker
    result = env.reset(**kwargs)
TypeError: reset() got an unexpected keyword argument 'seed'
```

**Comment by araffin** [comment]
please follow the issue template and don't check required items if you didn't do what's written:

> I have provided a https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014 example to reproduce the bug
I have checked my env using the env checker

**Comment by woipi90** [comment]
just one question are you using the latest sb3 version? So i mean SB3 version=2.0.0, or can you upgrade and test again?

**Comment by acq3047** [comment]
Hi @woipi90, I am using the latest version of SB3

**Comment by yiptsangkin** [comment]
same problem

**Comment by woipi90** [comment]
did you already try the check_env(env) method - did you check wheter the environment is also gymnasium compatible?

**Comment by reo-g** [comment]
@acq3047
I found same issue 

Solution:
gymnasium.Env.reset must include seed parameter 
`super().reset(seed=seed)`

https://gymnasium.farama.org/api/env/#gymnasium.Env.reset

**Comment by Hijackoo** [comment]
same problem

**Comment by BND-lhr** [comment]
> > [@acq3047](https://github.com/acq3047) I found same issue
> > Solution: gymnasium.Env.reset must include seed parameter `super().reset(seed=seed)`
> > https://gymnasium.farama.org/api/env/#gymnasium.Env.reset
> 
> It works. But I got another issue "not enough values to unpack (expected 2, got 1)"
I get the solution:
