### ISSUE TITLE
[Bug]: Rich LiveError - Only one live display may be active at once

### ISSUE THREAD

**Issue by xmatthias** [DLR-RM/stable-baselines3#1645]
### 🐛 Bug

When using Stable baselines with `progress_bar=True`, it seems like the progressbar is not properly finalized / closed if the environment raises an error - leaving the so-called LiveDisplay open, preventing further use of rich.

In theory, that's not a problem, unless there's error-handling in place which starts another training run - where the process will then fail - or if there's other Rich-code after the failure which would also fail.

The example below is obviously a VERY dumb example i've created to reproduce this independently. 

On a quick analysis, it seems like the `_on_training_end` method is never called - causing the progressbar to never finalize.

https://github.com/DLR-RM/stable-baselines3/blob/ba77dd7c6180c0ec9a47dfa98291c2103e6750df/stable_baselines3/common/callbacks.py#L689C9-L692

### To Reproduce

```python
import gymnasium as gym
import numpy as np
from gymnasium import spaces
from stable_baselines3 import A2C

N_DISCRETE_ACTIONS = 5
class CustomEnv(gym.Env):
    """Custom Environment that follows gym interface."""

    metadata = {"render_modes": ["human"], "render_fps": 30}

    def __init__(self):
        super().__init__()
        # Define action and observation space
        # They must be gym.spaces objects
        # Example when using discrete actions:
        self.action_space = spaces.Discrete(N_DISCRETE_ACTIONS)
        # # Example for using image as input (channel-first; channel-last also works):
        self.observation_space =  gym.spaces.Box(0, 1, shape=(20,), dtype=np.float32)

    def step(self, action):
        observation = np.random.random(20)
        reward = np.random.random()
        terminated = False
        truncated = False
        if (np.random.random() < 0.1):
            # terminated = True
            raise ValueError()
        return observation, reward, terminated, truncated, {}

    def reset(self, seed=None, options=None):
        ...
        observation = np.random.random(20)
        return observation, {}

    def render(self):
        ...

    def close(self):
        ...


# env = gym.make("CartPole-v1", render_mode="rgb_array")
env = CustomEnv()

model = A2C("MlpPolicy", env, verbose=1)
try:
    model.learn(total_timesteps=10_000, progress_bar=True)
except:
    # Cause Rich error
    model.learn(total_timesteps=2_000, progress_bar=True)

```

### Relevant log output / Error message

```shell
Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Traceback (most recent call last):
  File "/home/xmatt/devel/cryptos/freqtrade_copy/scripts/gymnasium_repro.py", line 48, in <module>
    model.learn(total_timesteps=10_000, progress_bar=True)
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/stable_baselines3/a2c/a2c.py", line 194, in learn
    return super().learn(
           ^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 259,
in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 178,
in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 
197, in step
    return self.step_wait()
           ^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 
58, in step_wait
    obs, self.buf_rews[env_idx], terminated, truncated, self.buf_infos[env_idx] = self.envs[env_idx].step(
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/stable_baselines3/common/monitor.py", line 94, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
                                                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/devel/cryptos/freqtrade_copy/scripts/gymnasium_repro.py", line 28, in step
    raise ValueError()
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xmatt/devel/cryptos/freqtrade_copy/scripts/gymnasium_repro.py", line 51, in <module>
    model.learn(total_timesteps=2_000, progress_bar=True)
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/stable_baselines3/a2c/a2c.py", line 194, in learn
    return super().learn(
           ^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 254,
in learn
    callback.on_training_start(locals(), globals())
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/stable_baselines3/common/callbacks.py", line 74, in 
on_training_start
    self._on_training_start()
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/stable_baselines3/common/callbacks.py", line 198, in 
_on_training_start
    callback.on_training_start(self.locals, self.globals)
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/stable_baselines3/common/callbacks.py", line 74, in 
on_training_start
    self._on_training_start()
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/stable_baselines3/common/callbacks.py", line 682, in 
_on_training_start
    self.pbar = tqdm(total=self.locals["total_timesteps"] - self.model.num_timesteps)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/tqdm/rich.py", line 113, in __init__
    self._prog.__enter__()
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/rich/progress.py", line 1168, in __enter__
    self.start()
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/rich/progress.py", line 1159, in start
    self.live.start(refresh=True)
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/rich/live.py", line 113, in start
    self.console.set_live(self)
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/rich/console.py", line 835, in set_live
    raise errors.LiveError("Only one live display may be active at once")
rich.errors.LiveError: Only one live display may be active at once
   0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/10,000  [ 0:00:00 < -:--:-- , ? it/s ]Exception ignored in: <function tqdm.__del__ at 0x7f0c759cf4c0>
Traceback (most recent call last):
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/tqdm/std.py", line 1145, in __del__
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/tqdm/rich.py", line 120, in close
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/rich/progress.py", line 1177, in __exit__
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/rich/progress.py", line 1163, in stop
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/rich/live.py", line 155, in stop
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/rich/console.py", line 1136, in line
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/rich/console.py", line 1673, in print
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/rich/console.py", line 1534, in _collect_renderables
  File "/home/xmatt/.pyenv/versions/trade_3112_copy/lib/python3.11/site-packages/rich/protocol.py", line 28, in rich_cast
ImportError: sys.meta_path is None, Python is likely shutting down
```
```


### System Info

- OS: Linux-6.4.7-arch1-3-x86_64-with-glibc2.38 # 1 SMP PREEMPT_DYNAMIC Wed, 02 Aug 2023 09:47:27 +0000
- Python: 3.11.2
- Stable-Baselines3: 2.0.0
- PyTorch: 2.0.1+cu117
- GPU Enabled: False
- Numpy: 1.25.2
- Cloudpickle: 2.2.1
- Gymnasium: 0.28.1
- OpenAI Gym: 0.21.0


### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

```python
try:
    model.learn(total_timesteps=10_000, progress_bar=True)
except:
    # Cause Rich error
    model.learn(total_timesteps=2_000, progress_bar=True)
```

why would you do such thing? It looks like you should catch the exception inside the environment instead of the agent.

Anyway, there is an easy fix if you want to use progress bar and restart model training after catching the errors:

```python
from stable_baselines3 import A2C
from stable_baselines3.common.callbacks import BaseCallback, ProgressBarCallback


class CustomCallback(BaseCallback):
    def _on_step(self) -> bool:
        raise ValueError("Oh no!")
        return True


callbacks = [CustomCallback(), ProgressBarCallback()]

model = A2C("MlpPolicy", "CartPole-v1", verbose=1)
try:
    model.learn(total_timesteps=10_000, callback=callbacks)
except ValueError:
    # close the progress bar
    callbacks[1].on_training_end()
    pbar_callback = ProgressBarCallback()
    model.learn(total_timesteps=2_000, callback=pbar_callback)
```

**Comment by xmatthias** [comment]
> why would you do such thing? It looks like you should catch the exception inside the environment instead of the agent.

don't disagree with this - it was a  simplified example from the actual usecase, maybe too simplified - as it makes it look dumb.

---

Based on your example, it's expected that `on_training_end()` is not called?
is there another callback (maybe `on_training_failed()`) which will be called in case of an error during training?

To me, this feels like a bug in the `ProgressBarCallback`. 
It's keeping resources open (LiveDisplay) - so unless it's being used in a one-off script - it's going to create problems in the longrun.

What you posted is a workaround - but it feels like an unnecessary workaround (callback "globals" should be cleaned up properly).

**Comment by araffin** [comment]
>  What you posted is a workaround

It is definitely a workaround but I would say it fits the provided code (which looks also like a workaround).

This is what we do in the RL Zoo (we only catch keyboard interrupt):
https://github.com/DLR-RM/rl-baselines3-zoo/blob/660f2d354ef9d63cd7a478390780dffa0cadb80c/rl_zoo3/exp_manager.py#L235-L248

> Based on your example, it's expected that on_training_end() is not called?

We would need to do a bare `except:` which catches everything including signal interrupt (like keyboard interrupt), memory leaks and any other exceptions. This would have more sides effects than letting the user deal with the exception properly I think.

The other thing is that `callbacks` is only a local variable.

**Comment by Neatt** [comment]
Hi,
Sorry if that issue is too old.
I'm commenting because I had to find my own solution because the other ones weren't working.
I'm posting it here in case it could help (sorry for the french comments) :
```python
#%% Trouver des objets (fermer les pbars buguées)
import gc

# On cherche tous les objets dont le nom du type contient tqdm
tqdm_objects = [obj for obj in gc.get_objects() if 'tqdm' in type(obj).__name__]

# On affiche leur type
for tqdm_object in tqdm_objects:
    print(type(tqdm_object).__name__)

# On ferme ceux qu'on veut
for tqdm_object in tqdm_objects:
    if 'tqdm_rich' in type(tqdm_object).__name__:
        tqdm_object.close()
