### ISSUE TITLE
got an unexpected keyword argument 'use_sde' when passing behavioural cloning policy to ppo

### ISSUE THREAD

**Issue by JkAcktuator** [DLR-RM/stable-baselines3#1672]
Hello,

I want to pass the policy learned from behavioural cloning in imitation library to ppo, I thought it would be successful since they are both from ActorCriticPolicy class, however it doesn't work as I expected. 

```
    from stable_baselines3 import PPO
    from imitation.algorithms import bc

    bc_trainer = bc.BC(
    observation_space=env.observation_space,
    action_space=env.action_space,
    device='cuda',
    policy=bc.reconstruct_policy(policy_path, device='cuda'),
    rng=rng,
    )
    model = PPO(policy=bc_trainer.policy, env=env, verbose=1, device = 'cuda')
```

I got the following error:

```
Traceback (most recent call last):
  File "agent/main.py", line 142, in <module>
    model = PPO(policy=bc_trainer.policy, env=env, verbose=1, device = 'cuda')
  File "/home/repos/stable-baselines3/stable_baselines3/ppo/ppo.py", line 164, in __init__
    self._setup_model()
  File "/home/repos/stable-baselines3/stable_baselines3/ppo/ppo.py", line 167, in _setup_model
    super()._setup_model()
  File "/home/repos/stable-baselines3/stable_baselines3/common/on_policy_algorithm.py", line 120, in _setup_model
    self.policy = self.policy_class(  # pytype:disable=not-instantiable
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'use_sde'
```

**System Info**
My environment:

- Pytorch 1.13.0
- Imitation 0.4.0
- running on Ubuntu 20.04.6 LTS
- Stable base line 1.8.0
- Python version 3.8.0
- Gym 0.21.0

**Comment by araffin** [comment]
Hello,
sounds like an issue from the imitation lib, not sb3.
