### ISSUE TITLE
[bug] Unexpected keyword argument "use_sde" in custom policy

### ISSUE THREAD

**Issue by jajimer** [DLR-RM/stable-baselines3#168]
I'm implementing an agent for a custom environment (it passed check_env), custom networks and custom ActorCriticPolicy. The environment has an MultiBinary(10) action space. Find below a code example.

I'm using self-implemented feature extractor and head networks inherit from BaseFeaturesExtractor and nn.Module respectively. When A2C or PPO tries to create the policy, the policy_kwargs argument fails. In the ActorCriticPolicy class use_sde is False by default, so I don't know what the problem may be.

```python
from lib import CustomEnv, CustomCNN, CustomNetwork
from stable_baselines3.common.policies import ActorCriticPolicy
from stable_baselines3.a2c import A2C

class CustomPolicy(ActorCriticPolicy):
    def __init__(
        self,
        observation_space: gym.spaces.Space,
        action_space: gym.spaces.Space,
        lr_schedule: Callable[[float], float],
    ):
        super(CustomPolicy, self).__init__(
            observation_space,
            action_space,
            lr_schedule,
            features_extractor_class=CustomCNN,
            normalize_images=False)

    def _build(self, lr_schedule: Callable[[float], float]) -> None:
        # Policy and value heads network
        self.mlp_extractor = CustomNetwork(self.features_dim)
        ...

env = CustomEnv()
agent = CustomPolicy(env.observation_space, env.action_space, lr_)
model = A2C(agent, env)
model.learn(1e5)
```

I got the following error:

```bash
Traceback (most recent call last):
  File "agent.py", line 131, in <module>
    model = A2C(agent, env)
  File "/home/jajimer/lib/python3.7/site-packages/stable_baselines3/a2c/a2c.py", line 109, in __init__
    self._setup_model()
  File "/home/jajimer/lib/python3.7/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 120, in _setup_model
    **self.policy_kwargs  # pytype:disable=not-instantiable
  File "/home/jajimer/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'use_sde'
```

**System Info**
My environment:
 * pip installation
 * Running on CPU and Ubuntu 18.04.2 LTS
 * Python version 3.7.3
 * PyTorch version 1.6.0
 * Gym version 0.17.2

Any help will be appreciated. Thanks in advance.

**Comment by Miffyli** [comment]
@araffin Could you take a look at this given it relates to the SDE stuff?

**Comment by araffin** [comment]
>Could you take a look at this given it relates to the SDE stuff?

This is related to #144 . I started updating the doc in #167 but it is not complete.
To be short, you can do (for PPO/A2C):

```python
class CustomActorCriticPolicy(ActorCriticPolicy):
    def __init__(
        self,
        observation_space: gym.spaces.Space,
        action_space: gym.spaces.Space,
        lr_schedule: Callable[[float], float],
        net_arch: Optional[List[Union[int, Dict[str, List[int]]]]] = None,
        activation_fn: Type[nn.Module] = nn.Tanh,
        *args,
        **kwargs,
    ):

        super(CustomActorCriticPolicy, self).__init__(
            observation_space,
            action_space,
            lr_schedule,
            net_arch,
            activation_fn,
            *args,
            **kwargs,
        )

    def _build(self, lr_schedule: Callable[[float], float]) -> None:
        self.mlp_extractor = MlpExtractor(self.features_dim, net_arch=self.net_arch, activation_fn=self.activation_fn)

        ...


```
so just passing the remaining arguments and keyword arguments to the constructor.

**Comment by jajimer** [comment]
Pretty cool! I made it with work from your reply but using ``CnnPolicy`` and ``net_arch``. This full example is great.
Thank you! Looking forward to the next release :)
