### ISSUE TITLE
[Bug]: "Exception ignored" message on save_to_zip when filtering

### ISSUE THREAD

**Issue by npit** [DLR-RM/stable-baselines3#1729]
### 🐛 Bug

If you save / load a model while catching warnings as errors with the `warnings` library, there are messages like:
`Exception ignored in: <_io.FileIO name='cartpole_model.zip' mode='wb' closefd=True>` 
every time the io operation is invoked, from `common/base_class.py` and the load / save to / from zip functions.

Removing the warning filtering removes all such messages.

It is unclear if that is expected behaviour, since no exception is raised and the program concludes normally.
Edit: removed the commenting-out of the warning filtering from the reproduction code.

### To Reproduce

```python
import os
import warnings
import numpy as np
import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv, VecMonitor
from stable_baselines3.common.callbacks import BaseCallback
from stable_baselines3.common.evaluation import evaluate_policy

class SaveModelCallback(BaseCallback):
    def __init__(self, save_freq, save_path):
        super().__init__()
        self.save_freq = save_freq
        self.save_path = save_path
        self.model = None

    def _on_step(self) -> bool:
        if self.num_timesteps > 0 and self.num_timesteps % self.save_freq == 0:
            self.model.save(self.save_path + f"_timestep_{self.num_timesteps}")
        return True

with warnings.catch_warnings():
    # catch warning as errors: including this
    # generates the ResourceWarning and Exception ignored messages
    warnings.filterwarnings('error')

    # Create a CartPole environment
    env = gym.make('CartPole-v1')

    # Wrap the environment in a DummyVecEnv
    env = DummyVecEnv([lambda: env])

    # Define the callback to save the model
    save_callback = SaveModelCallback(save_freq=1000, save_path="cartpole_model")

    # Create a PPO agent
    model = PPO("MlpPolicy", env, verbose=1)

    # Train the agent
    model.learn(total_timesteps=5000, callback=save_callback)

    # Save the final model
    model.save("cartpole_model_final")

    # load and eval
    print("Evaluating")
    model.load("cartpole_model_final")
    eval_env = VecMonitor(DummyVecEnv([lambda : gym.make('CartPole-v1')]))
    print(evaluate_policy(model, eval_env, n_eval_episodes=3))

```

### Relevant log output / Error message

```shell
$ python test.py
Using cuda device
Exception ignored in: <_io.FileIO name='cartpole_model_timestep_1000.zip' mode='wb' closefd=True>
Traceback (most recent call last):
  File "/home/nik/testsb3/venv/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 845, in save
    save_to_zip_file(path, data=data, params=params_to_save, pytorch_variables=pytorch_variables)
ResourceWarning: unclosed file <_io.BufferedWriter name='cartpole_model_timestep_1000.zip'>
Exception ignored in: <_io.FileIO name='cartpole_model_timestep_2000.zip' mode='wb' closefd=True>
Traceback (most recent call last):
  File "/home/nik/testsb3/venv/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 845, in save
    save_to_zip_file(path, data=data, params=params_to_save, pytorch_variables=pytorch_variables)
ResourceWarning: unclosed file <_io.BufferedWriter name='cartpole_model_timestep_2000.zip'>
-----------------------------
| time/              |      |
|    fps             | 1170 |
|    iterations      | 1    |
|    time_elapsed    | 1    |
|    total_timesteps | 2048 |
-----------------------------
Exception ignored in: <_io.FileIO name='cartpole_model_timestep_3000.zip' mode='wb' closefd=True>
Traceback (most recent call last):
  File "/home/nik/testsb3/venv/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 845, in save
    save_to_zip_file(path, data=data, params=params_to_save, pytorch_variables=pytorch_variables)
ResourceWarning: unclosed file <_io.BufferedWriter name='cartpole_model_timestep_3000.zip'>
Exception ignored in: <_io.FileIO name='cartpole_model_timestep_4000.zip' mode='wb' closefd=True>
Traceback (most recent call last):
  File "/home/nik/testsb3/venv/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 845, in save
    save_to_zip_file(path, data=data, params=params_to_save, pytorch_variables=pytorch_variables)
ResourceWarning: unclosed file <_io.BufferedWriter name='cartpole_model_timestep_4000.zip'>
-----------------------------------------
| time/                   |             |
|    fps                  | 936         |
|    iterations           | 2           |
|    time_elapsed         | 4           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.008844521 |
|    clip_fraction        | 0.128       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.686      |
|    explained_variance   | -0.0068     |
|    learning_rate        | 0.0003      |
|    loss                 | 7.76        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0188     |
|    value_loss           | 53.9        |
-----------------------------------------
Exception ignored in: <_io.FileIO name='cartpole_model_timestep_5000.zip' mode='wb' closefd=True>
Traceback (most recent call last):
  File "/home/nik/testsb3/venv/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 845, in save
    save_to_zip_file(path, data=data, params=params_to_save, pytorch_variables=pytorch_variables)
ResourceWarning: unclosed file <_io.BufferedWriter name='cartpole_model_timestep_5000.zip'>
Exception ignored in: <_io.FileIO name='cartpole_model_timestep_6000.zip' mode='wb' closefd=True>
Traceback (most recent call last):
  File "/home/nik/testsb3/venv/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 845, in save
    save_to_zip_file(path, data=data, params=params_to_save, pytorch_variables=pytorch_variables)
ResourceWarning: unclosed file <_io.BufferedWriter name='cartpole_model_timestep_6000.zip'>
-----------------------------------------
| time/                   |             |
|    fps                  | 882         |
|    iterations           | 3           |
|    time_elapsed         | 6           |
|    total_timesteps      | 6144        |
| train/                  |             |
|    approx_kl            | 0.008360811 |
|    clip_fraction        | 0.0382      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.668      |
|    explained_variance   | 0.0765      |
|    learning_rate        | 0.0003      |
|    loss                 | 13.7        |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.0113     |
|    value_loss           | 42.3        |
-----------------------------------------
Exception ignored in: <_io.FileIO name='cartpole_model_final.zip' mode='wb' closefd=True>
Traceback (most recent call last):
  File "/home/nik/testsb3/venv/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 845, in save
    save_to_zip_file(path, data=data, params=params_to_save, pytorch_variables=pytorch_variables)
ResourceWarning: unclosed file <_io.BufferedWriter name='cartpole_model_final.zip'>
Evaluating
Exception ignored in: <_io.FileIO name='cartpole_model_final.zip' mode='rb' closefd=True>
Traceback (most recent call last):
  File "/home/nik/testsb3/venv/lib/python3.8/site-packages/stable_baselines3/common/base_class.py", line 679, in load
    data, params, pytorch_variables = load_from_zip_file(
ResourceWarning: unclosed file <_io.BufferedReader name='cartpole_model_final.zip'>
(339.66666, 131.04791)

$ ls
cartpole_model_final.zip          cartpole_model_timestep_2000.zip  cartpole_model_timestep_4000.zip  cartpole_model_timestep_6000.zip
cartpole_model_timestep_1000.zip  cartpole_model_timestep_3000.zip  cartpole_model_timestep_5000.zip  test.py
```

### System Info

- OS: Linux-6.5.9-arch2-1-x86_64-with-glibc2.34 # 1 SMP PREEMPT_DYNAMIC Thu, 26 Oct 2023 00:52:20 +0000
- Python: 3.8.15
- Stable-Baselines3: 2.0.0
- PyTorch: 1.13.1+cu117
- GPU Enabled: True
- Numpy: 1.24.1
- Cloudpickle: 2.2.1
- Gymnasium: 0.28.1

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
thanks for reporting the issue, I was able to reproduce the issue using:
```python
from stable_baselines3 import PPO

# Create a PPO agent and save it
model = PPO("MlpPolicy", "CartPole-v1").save("cartpole_model")
```
and
```
PYTHONWARNINGS=default python test.py
```

I will try to push a simple fix soon: we need to call `save_path.close()` in `save_to_zip_file` (or use a context manager).
