### ISSUE TITLE
[Bug]: DummyVecEnv isn't compatible with gym v26 or gymnasium v26 new standards

### ISSUE THREAD

**Issue by tty666** [DLR-RM/stable-baselines3#1730]
### 🐛 Bug

Hello I had an old style hyperoptimization script still working fine (using optuna) but when I took a look deeply into the code of the script I found that :

```
# Évaluez les performances du modèle
    obs = env.reset()
    total_rewards = 0
    for _ in range(1000):
        action, _states = model.predict(obs)
        obs, rewards, done, info = env.step(action)
        total_rewards += rewards
        if done:
            break
```
Which works ! Where it shouldn't work anymore !!!
It should look like this with gymnasium V26/Gym V26 :

```
    # Évaluez les performances du modèle
    obs,info = env.reset()
    total_rewards = 0
    for _ in range(1000):
        action, _states = model.predict(obs)
        obs, rewards, terminated, truncated, info = env.step(action)
        total_rewards += rewards
        if terminated or truncated:
            break
```
            
I deep dived then how I was creating the environment and I found that :

def optimize_with_env(study_name, storage_name):
    stock_env = StockTradingEnv(data[symbol_to_train], live=0, random_start=random_start)
    DummyVecEnv([lambda: stock_env])
    #env = VecNormalize(env, norm_obs=False, norm_reward=True)
    study = optuna.load_study(study_name=study_name, storage=storage_name)
    study.optimize(lambda trial: objective(env, trial), n_trials=16, callbacks=[save_trial])
    return study
    
   So I checked why we still get "done" working as it shouldn't ! and also only delivers observation as a result of the env.reset ... (where it should be now observation, info )
   And the answer is : 
`   DummyVecEnv([lambda: stock_env])`
So I don't understand, should we have an update of the DummyVecEnv class to be compliant with V26 ? Or should we keep using done ? but then what is the result of the truncated/terminated ? is only terminated interpreted and returned with dummyvecenv ? as the distinction doesn't exists in the DummyVecEnv class ?!? I am totally lost here and ask for your expertise !

### To Reproduce

```python
from stable_baselines3 import ...

```
Just look the comment it explains it.

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
    r = call_item()
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "02_hyperoptimize.py", line 129, in optimize_with_env
    study.optimize(lambda trial: objective(env, trial), n_trials=16, callbacks=[save_trial])
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/site-packages/optuna/study/study.py", line 425, in optimize
    _optimize(
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "02_hyperoptimize.py", line 129, in <lambda>
    study.optimize(lambda trial: objective(env, trial), n_trials=16, callbacks=[save_trial])
  File "02_hyperoptimize.py", line 115, in objective
    obs, rewards, terminated, truncated, info = env.step(action)
ValueError: not enough values to unpack (expected 5, got 4)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "02_hyperoptimize.py", line 150, in <module>
    studies = parallel(delayed(optimize_with_env)(study_name, storage_name) for _ in range(n_jobs))
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/site-packages/joblib/parallel.py", line 1098, in __call__
    self.retrieve()
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/site-packages/joblib/parallel.py", line 975, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/Users/tty666/miniforge3/envs/finRL/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
ValueError: not enough values to unpack (expected 5, got 4)

If we use the new "terminated" and "truncated" output of step ...
```

### System Info

python 3.8.16 with latest version of stable-baselines3 :

- OS: macOS-14.1-arm64-arm-64bit Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000
- Python: 3.8.16
- Stable-Baselines3: 2.1.0
- PyTorch: 2.1.0
- GPU Enabled: False
- Numpy: 1.23.2
- Cloudpickle: 2.2.1
- Gymnasium: 0.28.1
- OpenAI Gym: 0.26.2

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)


https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html#vecenv-api-vs-gym-api

**Comment by tty666** [comment]
Thanks for the warning Araffin :D 
I am not really doing stock but crypto it's even worst ! but anyway :) that's my problem ;)
Now if the answer is the documentation sorry for that as I wasn't able to find it by myself ! will read it deeply thanks for this !
