### ISSUE TITLE
problem to do custom environment parallel processing

### ISSUE THREAD

**Issue by alyssoncrvg** [DLR-RM/stable-baselines3#1748]
### 🐛 Bug

**My initial idea is to create a scenario where a multi-process occurs in several identical environments where a single agent will be present in each of them, but in the future I want to make them communicate so that information can be exchanged between them. However, my initial problem is how to make these environments process in parallel.**

**An error is occurring when trying to parallelize the environment using both make_vec_env and SubprocVecEnv, the project only runs using DummyVecEnv**

### Code example

```python
import gymnasium as gym
import numpy as np
from gymnasium import spaces
from stable_baselines3.common.monitor import Monitor

from stable_baselines3 import PPO
from stable_baselines3.common.env_checker import check_env

class Somn(Env):

    """Custom Environment that follows gym interface."""
    def __init__(
        self,
        M: int,
        N: int,
        Y: int,
        MAXDO: int,
        MAXAM: int,
        MAXPR: int,
        MAXPE: int,
        MAXFT: int,
        MAXMT: int,
        MAXTI: int,
        MAXEU: int,
        #seed: int,
        atraso: int = None
    ):
        super(Somn).__init__()
       super(Somn).__init__()

        Somn.priorqpr = heapdict()
        # Somn.instance = JobShop()
        # Somn.priorqsu = heapdict()
        # Somn.priorqva = heapdict()
        Somn.time = 1
        Somn.objetivo = 1

        self.M = M
        self.N = N
        self.Y = Y
        self.MAXDO = MAXDO
        self.MAXAM = MAXAM
        self.MAXPR = MAXPR
        self.MAXPE = MAXPE
        self.MAXFT = MAXFT
        self.MAXMT = MAXMT
        self.MAXTI = MAXTI
        self.MAXEU = MAXEU
        # self.MT = np.random.randint(0,MAXFT,M)
        self.EU = np.random.random(M) * MAXEU
        self.BA = np.random.randint(0, MAXFT, M)
        self.IN = np.random.randint(0, MAXFT, M)
        self.OU = np.random.randint(0, MAXFT, M)
        #self.seed = seed
        self.atraso = atraso # (by_frederic)
        # self.state = np.zeros((N,5))

        # print('Inicializado', M, N , Y)

        self.DE = [
            Demand(
                M, N, MAXDO, MAXAM, MAXPR, MAXPE, MAXFT, MAXMT, MAXTI, MAXEU, Somn.time, self.atraso
            )
            for _ in range(N)
        ]
        self.YA = [Yard(Y, M, MAXFT) for _ in range(Y)]
        self.action_space = spaces.Discrete(self.MAXDO)

        self.observation_space = spaces.Dict(
            {
                "time": spaces.Box(low=0.0, high=1.0, shape=(1,), dtype=np.float64),
                "MT": spaces.Box(low=0.0, high=1.0, shape=(self.M,), dtype=np.float64),
                "EU": spaces.Box(low=0.0, high=1.0, shape=(self.M,), dtype=np.float64),
                "BA": spaces.Box(low=0.0, high=1.0, shape=(self.M,), dtype=np.float64),
                "IN": spaces.Box(low=0.0, high=1.0, shape=(self.M,), dtype=np.float64),
                "OU": spaces.Box(low=0.0, high=1.0, shape=(self.M,), dtype=np.float64),
                "state": spaces.Box(
                    low=0.0, high=1.0, shape=(self.N, 4), dtype=np.float64
                ),
            }
        )
       ...

def custom_make_env(atraso: int = None):
    env = Somn(Y=3,M=10,N=10,MAXDO=10,MAXAM=3,MAXPR=2,MAXPE=10,MAXFT=5,MAXMT=3,MAXTI=2,
               MAXEU = 5, atraso=atraso)
    env = Monitor(env)  # record stats such as returns
    return env


if __name__ == "__main__":

            env1 = SubprocVecEnv([lambda: custom_make_env(atraso) for _ in range(2)])
            # env1 = make_vec_env(custom_make_env(atraso), n_envs=4)
  
            model = PPO(
                policy="MultiInputPolicy",
                env=env1,
                learning_rate=config.learning_rate,
                n_steps=config.n_steps,
                batch_size=config.batch_size,
                n_epochs=config.n_epochs,
                gamma=config.gamma,
                gae_lambda=config.gae_lambda,
                #clip_range=config.clip_range,
                ent_coef=config.ent_coef,
                #vf_coef=config.vf_coef,
                #max_grad_norm=config.max_grad_norm,
                target_kl=config.target_kl,
                #stats_window_size=config.stats_window_size,
                verbose=0,
                #seed = 2023,
                device='cpu',
                #tensorboard_log=f"/content/drive/MyDrive/SOMN2/runs/{run1.id}"
                tensorboard_log=f"runs/{run1.id}"
            )
              
  
              model.learn(total_timesteps=3328*400)
```

### Relevant log output / Error message

```shell
**When using custom_make_env it returns the following error:**
Traceback (most recent call last):
  File "c:\Users\Alysson\Desktop\SOMN\Treinamento.py", line 52, in <module>
    env1 = make_vec_env(custom_make_env(atraso), n_envs=4)
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\env_util.py", line 125, in make_vec_env
    vec_env = vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 30, 
in __init__
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py", line 30, 
in <listcomp>
    self.envs = [_patch_env(fn()) for fn in env_fns]
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\env_util.py", line 98, in _init     
    env = env_id(**env_kwargs)
TypeError: 'Monitor' object is not callable

**When using SubprocVecEnv, the following error is returned:**
Process SpawnProcess-1:
Process SpawnProcess-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py", line 46, in _worker
    observation, reset_info = env.reset(seed=data[0], **maybe_options)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\monitor.py", line 83, in reset      
    return self.env.reset(**kwargs)
  File "c:\Users\Alysson\Desktop\SOMN\Ambiente_SOMN\Somn.py", line 545, in reset
    wandb.log({
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py", line 46, in _worker
    observation, reset_info = env.reset(seed=data[0], **maybe_options)
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\wandb\sdk\lib\preinit.py", line 36, in preinit_wrapper       
    raise wandb.Error(f"You must call wandb.init() before {name}()")
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\monitor.py", line 83, in reset      
    return self.env.reset(**kwargs)
wandb.errors.Error: You must call wandb.init() before wandb.log()
  File "c:\Users\Alysson\Desktop\SOMN\Ambiente_SOMN\Somn.py", line 545, in reset
    wandb.log({
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\wandb\sdk\lib\preinit.py", line 36, in preinit_wrapper       
    raise wandb.Error(f"You must call wandb.init() before {name}()")
wandb.errors.Error: You must call wandb.init() before wandb.log()
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 317, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] O pipe foi finalizado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Alysson\Desktop\SOMN\Treinamento.py", line 77, in <module>
    model.learn(total_timesteps=3328*400)
  File "c:\Users\Alysson\Desktop\SOMN\Stablebaselines3\PPO.py", line 441, in learn
    return super().learn(
  File "c:\Users\Alysson\Desktop\SOMN\Stablebaselines3\OnPolicyAlgirithm.py", line 247, in learn
    total_timesteps, callback = self._setup_learn(
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\base_class.py", line 423, in _setup_learn
    self._last_obs = self.env.reset()  # type: ignore[assignment]
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py", line 137, in reset
    results = [remote.recv() for remote in self.remotes]
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py", line 137, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 326, in _recv_bytes
    raise EOFError
EOFError
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Your logs are not consistent with the code you provide:

> ```python
> #env1 = make_vec_env(custom_make_env(atraso), n_envs=4)
> ```

> ```
> File "c:\Users\Alysson\Desktop\SOMN\Treinamento.py", line 52, in <module>
>     env1 = make_vec_env(custom_make_env(atraso), n_envs=4)
> ```

Also, I think it's just that you're trying to log something with wandb within your env, but you haven't initialized the project:

> ```
>   File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\wandb\sdk\lib\preinit.py", line 36, in preinit_wrapper       
    raise wandb.Error(f"You must call wandb.init() before {name}()")
> ```

If this doesn't solve your problem, please make the effort to reduce your code as much as possible and provide system information, otherwise we won't be able to help you.

**Comment by alyssoncrvg** [comment]
**wandb is being initialized correctly, because if I use DummyVecEnv the project runs correctly. The problem is when I try to use SubprocVecEnv or make_vec_env, as the code is very robust and separated by several folders, I will provide the code here where I use the complete training if that is better**
```python
import os
import wandb
import time
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.vec_env import DummyVecEnv, VecVideoRecorder, SubprocVecEnv
from stable_baselines3.common.env_util import make_vec_env

from Ambiente_SOMN.custom_make_env import custom_make_env
from Stablebaselines3.PPO import PPO
from Ambiente_SOMN.Yard import Yard

if len(wandb.patched["tensorboard"]) > 0:
    wandb.tensorboard.unpatch()
#wandb.tensorboard.patch(root_logdir="/content/drive/MyDrive/SOMN2/runs")
wandb.tensorboard.patch(root_logdir="./runs")

if __name__ == "__main__":

    for atraso in range(-1,0,10):
        config_PPO = {
            'atraso': atraso,
            'batch_size': 256,
            'ent_coef': 0.001641577520175419,
            'gae_lambda': 0.9142950466044,
            'gamma': 0.918623650457886,
            'learning_rate': 0.0003660144793262825,
            'n_epochs': 21,
            'n_steps': 3328,
            'target_kl': 0.02113910446426361
        }

        for x in range(1): 
            run1 = wandb.init(project='Testes',
                            config=config_PPO,
                            group=f'windowns 10',
                            name=f'Case 2',
                            save_code=True,
                            reinit=True
            )

            config = wandb.config
            env1 = SubprocVecEnv([lambda: custom_make_env(atraso) for _ in range(2)])

            model = PPO(
                policy="MultiInputPolicy",
                env=env1,
                learning_rate=config.learning_rate,
                n_steps=config.n_steps,
                batch_size=config.batch_size,
                n_epochs=config.n_epochs,
                gamma=config.gamma,
                gae_lambda=config.gae_lambda,
                ent_coef=config.ent_coef,
                target_kl=config.target_kl,
                verbose=0,
                device='cpu',
                tensorboard_log=f"runs/{run1.id}"
            )
            

            model.learn(total_timesteps=3328*400)
            
            model.save(os.path.join(wandb.run.dir, f"model_custom_PPO_atraso_{atraso:02d}"))
            wandb.finish()
```

**Comment by qgallouedec** [comment]
Duplicate https://github.com/wandb/wandb/issues/5087

This is probably because wandb can't be used in multiple threads. I'm not sure what you're trying to do, but the safest way is probably to use a callback to log, and avoid doing it in your env.

**Comment by alyssoncrvg** [comment]
**I'm trying to create several environments where each environment has its unique agent working and I'm going to try to make them communicate in the future, the way I first thought of was processing environments in parallel.
I removed wandb to try training, and the following error is returning me:**
```error
Process SpawnProcess-2:
Process SpawnProcess-1:
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py", line 46, in _worker
    observation, reset_info = env.reset(seed=data[0], **maybe_options)
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py", line 46, in _worker
    observation, reset_info = env.reset(seed=data[0], **maybe_options)
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\monitor.py", line 83, in reset      
    return self.env.reset(**kwargs)
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\monitor.py", line 83, in reset      
    return self.env.reset(**kwargs)
  File "c:\Users\Alysson\Desktop\SOMN\Ambiente_SOMN\Somn.py", line 545, in reset
    wandb.log({
  File "c:\Users\Alysson\Desktop\SOMN\Ambiente_SOMN\Somn.py", line 545, in reset
    wandb.log({
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\wandb\sdk\lib\preinit.py", line 36, in preinit_wrapper
    raise wandb.Error(f"You must call wandb.init() before {name}()")
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\wandb\sdk\lib\preinit.py", line 36, in preinit_wrapper       
    raise wandb.Error(f"You must call wandb.init() before {name}()")
wandb.errors.Error: You must call wandb.init() before wandb.log()
wandb.errors.Error: You must call wandb.init() before wandb.log()
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 317, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] O pipe foi finalizado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Alysson\Desktop\SOMN\Treinamento.py", line 77, in <module>
    model.learn(total_timesteps=3328*400)
  File "c:\Users\Alysson\Desktop\SOMN\Stablebaselines3\PPO.py", line 441, in learn
    return super().learn(
  File "c:\Users\Alysson\Desktop\SOMN\Stablebaselines3\OnPolicyAlgirithm.py", line 247, in learn
    total_timesteps, callback = self._setup_learn(
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\base_class.py", line 423, in _setup_learn
    self._last_obs = self.env.reset()  # type: ignore[assignment]
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py", line 137, in reset
    results = [remote.recv() for remote in self.remotes]
  File "C:\Users\Alysson\Desktop\SOMN\.venv\lib\site-packages\stable_baselines3\common\vec_env\subproc_vec_env.py", line 137, in <listcomp>
    results = [remote.recv() for remote in self.remotes]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\multiprocessing\connection.py", line 326, in _recv_bytes
    raise EOFError
EOFError
```

**Comment by alyssoncrvg** [comment]
It worked, thank you very much! There were several excerpts that reference wandb spread throughout the files. I'm unsure if it's possible to make these agents communicate with each other and if there's a way to put the results differently from each environment into a single logger. As I used wandb, I'm a bit out of touch with other ways that can be used.

**Comment by qgallouedec** [comment]
The proposed baselines assume that the environment is markovian and therefore does not depend on external variables. What I understand sounds more like MARL with communication, so I suggest you consult the literature on the subject. Anyway,the initial issue is solved, I close the issue. 
😊
