### ISSUE TITLE
IsaacGym Preview4 with Stable Baselines3?

### ISSUE THREAD

**Issue by LyuJZ** [DLR-RM/stable-baselines3#1768]
Hi, thanks a lot for the well-documented stable baselines3. Now I am using Isaac Gym Preview4. May I ask if it is possible to give some examples to wrap IsaacGymEnvs into VecEnv? I noticed this issue was mentioned before. And some tips have been given in the issue https://github.com/DLR-RM/stable-baselines3/issues/772. However, it seems it is for Isaac Gym Preview3. Could you give one example for Isaac Gym Preview 4?

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
what have you tried so far (see also links in our doc, please provide minimal and working code) and what is the current issue?

**Comment by LyuJZ** [comment]
I found the problems. It is because I redefine abstract methods. Now I changed these abstract methods as follow:
```
    def step_async(self, actions):  # noqa: D102
        self._async_actions = actions

    def step_wait(self):  # noqa: D102
        return self.step(self._async_actions)

    def get_attr(self, attr_name, indices=None):  # noqa: D102
        return self.env.get_attr(attr_name, indices)
        # raise NotImplementedError

    def set_attr(self, attr_name, value, indices=None):  # noqa: D102
        return self.env.set_attr(attr_name, value, indices)

    def env_method(self, method_name: str, *method_args, indices=None, **method_kwargs):  # noqa: D102
        return self.env.env_method(method_name, *method_args, indices=indices, **method_kwargs)

    def env_is_wrapped(self, wrapper_class, indices=None):  # noqa: D102
        return self.env.env_is_wrapped(wrapper_class, indices=indices)

    def get_images(self):  # noqa: D102
        return self.env.get_images()
```
Now, I got new errors like this:
```
Traceback (most recent call last):
  File "/src/handover-rl/kuka-reaching/wrappers.py", line 215, in launch_rlg_hydra
    sb3Env = Sb3VecEnvWrapper(envs)
  File "/src/handover-rl/kuka-reaching/wrappers.py", line 20, in __init__
    VecEnv.__init__(self, self.env.num_envs, self.env.observation_space, self.env.action_space)
  File "/anaconda3/envs/acmpc/lib/python3.8/site-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 83, in __init__
    self.render_mode = render_modes[0]
AttributeError: can't set attribute
```

**Comment by araffin** [comment]
Hmm, it's weird that the wrapper is deriving from both gym Wrapper and SB3 VecEnv and I guess that's the issue.

See https://github.com/Farama-Foundation/Gymnasium/blob/2f19f3ed69b9423444ec6f7cfa46c5fb079168c5/gymnasium/core.py#L440-L443

So if you only derive from `VecEnv` it should make things simpler.

**Comment by LyuJZ** [comment]
Is it possible to give one example to wrap IsaacGym VecEnv into sb3 VecEnv?

**Comment by LyuJZ** [comment]
I revised the code a little bit and now it works! Thanks a lot

**Comment by yinzikang** [comment]
hello, I want to combine the IsaacGym Preview4 with sb3 and get rid of the rlgames, just like you do I guess. 

So I am trying to reproduce what you have done. Precisely, I 
1. created a python file next to the `train.py` which can be used for rlgames-based training, 
2. copied and edited the code you provided in this issue according to the advice from araffin
3. choose the Cartpole task and run the code

however, there seems to be some other modification to make it work. Could you please share the whole code?

**Comment by araffin** [comment]
Note: IsaacGym is deprecated and Isaac Lab has an official wrapper: https://github.com/isaac-sim/IsaacLab/blob/main/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/utils/wrappers/sb3.py

I will update the doc soon
