### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'reset'

### ISSUE THREAD

**Issue by Hijackoo** [DLR-RM/stable-baselines3#1774]
### 🐛 Bug

I have encountered a problem similar to issue [#1694](https://github.com/DLR-RM/stable-baselines3/issues/1694), but when I attempted to resolve it using the following code:
```
vec_env = model.get_env()
obs = vec_env.reset()
model.predict(obs)
```
I encountered an` AttributeError: 'NoneType' object has no attribute 'reset'`. 
During training, I stored the model using 
`model.save("policy-" + identifier) `
When debugging, I observed that the type of `model.env` is` DummyVecEnv`. 
![image](https://github.com/DLR-RM/stable-baselines3/assets/46584550/d07f6bc8-dbc5-4cbd-80f8-858f95b89ea9)
However, when I load the previously stored model for testing using `model = TRPO.load("policy-" + identifier)`, I encounter the mentioned error. Upon closer inspection, it seems that the `model.env` is None at this point, indicating that it may not have been successfully saved.  It seems that the '`env`' key is not present in the '`data`' file inside the zip file saved by `model.save`.
![image](https://github.com/DLR-RM/stable-baselines3/assets/46584550/9d84da46-1fc8-4992-b4af-4d9aa8145afc)
 `env_checker.check_env` has passed, and the model `model` has been successfully trained.

### To Reproduce

```python
##`env` is a defined environment.
env = Environment(
    ...
)
class Environment(gym.Env):(...)

parser = argparse.ArgumentParser()
args = parser.parse_args()
# If True, train. Otherwise run trained policy
args.TRAIN = False
algo = PPO
if args.TRAIN:
    model = algo(env=env, verbose=1, seed=args.SEED, **items)
    model.set_env(env)
    model.learn(total_timesteps=int(args.total_timesteps))
    model.save("policy-" + identifer) ##"policy-" + identifer is the storage path.
else:
    model = PPO.load("policy-" + identifer)
    vec_env = model.get_env()
    obs = vec_env.reset()
```

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2022.2.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2022.2.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "J:\MasterDegree\SoftSimu\Elastica\PyElastica-master\Elastica-RL-control-main\Case2\logging_bio_args.py", line 237, in <module>
    obs = vec_env.reset()
AttributeError: 'NoneType' object has no attribute 'reset'
```

### System Info

'OS': 'Windows-10-10.0.22621-SP0 10.0.22621',
  'Python': '3.9.18',
  'Stable-Baselines3': '2.2.1',
  'PyTorch': '2.1.1+cu121',
  'GPU Enabled': 'True',
  'Numpy': '1.22.4',
  'Cloudpickle': '2.0.0',
  'Gymnasium': '0.29.1'},

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
From the doc:

```python
model = PPO.load("dqn_lunar", env=env)
```

https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#basic-usage-training-saving-loading
