### ISSUE TITLE
[Bug]: "too many values to unpack (expected 2)" when using FlattenObservation and env.reset()

### ISSUE THREAD

**Issue by ahrboktrexon** [DLR-RM/stable-baselines3#1783]
### 🐛 Bug

I am trainig a A2C agent using SB3 and an OpenAI Gym custom env... in order to use monitor and so on I am trying to use FrattenObservation to convert dict spaces, but when I call the env.reset() the error in title is thrown.

### To Reproduce

```import gym
from gym import spaces
import numpy as np

from stable_baselines3 import A2C
from gym.wrappers import FlattenObservation

class CustomEnv(gym.Env):
	def __init__(self):
		super().__init__()
		self.action_space = gym.spaces.MultiDiscrete((3, 3))
		self.observation_space = gym.spaces.Dict(
			{
				'key0': spaces.Discrete(2),
				"key1": gym.spaces.Box(low=0, high=np.inf, shape=(1,)),
				"key2": gym.spaces.Box(low=0, high=np.inf, shape=(1,)),
			},
		)
		pass

	def reset(self):

		return self.observation_space.sample()

	def step(self, action):
		return self.observation_space.sample(), 0, False, {}


env = CustomEnv()

env = FlattenObservation(env)
env.reset()
model = A2C("MlpPolicy", env)

```

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "/home/ahrboktrexon/projects/Agents/test-agemt/reproduce_error.py", line 32, in <module>
    env.reset()
  File "/home/ahrboktrexon/anaconda3/envs/test-agent/lib/python3.9/site-packages/gym/core.py", line 379, in reset
    obs, info = self.env.reset(**kwargs)
ValueError: too many values to unpack (expected 2)
```

### System Info

- OS: Linux-6.2.0-37-generic-x86_64-with-glibc2.35 # 38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2
- Python: 3.9.18
- Stable-Baselines3: 2.1.0
- PyTorch: 2.1.1+cu121
- GPU Enabled: True
- Numpy: 1.26.2
- Cloudpickle: 3.0.0
- Gymnasium: 0.29.1
- OpenAI Gym: 0.26.2

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by qgallouedec** [comment]
Hi, you should use gymnasium instead of gym. And use the `check_env` also (cf the doc). If the issue remains, please open a new issue under the right template (custom env) and be especially careful not to check the checkboxes without fulfilling the associated item.

> * [x]  My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
> * [x]  I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)

**Comment by ahrboktrexon** [comment]
Thank you so mutch @qgallouedec , my bad... I spent more time on reading the docs and followed your advice to migrate to gymnasium, problem solved! Thank you
