### ISSUE TITLE
How to make maskable custom environment vectorized by SubprocVecEnv

### ISSUE THREAD

**Issue by 0Addicted0** [DLR-RM/stable-baselines3#1793]
### 🐛 Bug

I have followed the document to train my custom MaskablePPO model in my custom environment successfully. But to train faster, i want to do it by SubprocVecEnv. However, i don't know how to pass the parameter to wrapper(ActionMasker). I try it by the following method, but it doesn't work.

### Code example

```python
import gymnasium as gym
import numpy as np
from gymnasium import spaces

from stable_baselines3 import A2C
from stable_baselines3.common.env_checker import check_env


class CustomEnv(gym.Env):

    def __init__(self):
        super().__init__()
        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(10, 10))
        self.action_space = spaces.Discrete(60)

    def reset(self, seed=None, options=None):
        return self.observation_space.sample(), {}

    def step(self, action):
        obs = self.observation_space.sample()
        reward = 1.0
        terminated = False
        truncated = False
        info = {}
        return obs, reward, terminated, truncated, info

# env = CustomEnv()
# check_env(env)

def mask_fn(env: CustomEnv) -> np.ndarray:
      # Do whatever you'd like in this function to return the action mask
      # for the current env. In this example, we assume the env has a
      # helpful method we can rely on.
      return env.valid_action_mask()

if __name__=='__main__':
    wrapper_config = dict(action_mask_fn=mask_fn)
    num_cpu = 2
    vec_env = make_vec_env(CustomEnv,
                           wrapper_class=ActionMasker, wrapper_kwargs=dict(action_mask_fn=wrapper_config),
                           n_envs = num_cpu, vec_env_cls=SubprocVecEnv)
    # Train MaskablePPO on the environment
    model = MaskablePPO(CustomMaskableActorCriticPolicy, vec_env, verbose=1, 
                   policy_kwargs=policy_kwargs,
                   n_steps=5)
```

### Relevant log output / Error message

```shell
Process ForkServerProcess-1:
Process ForkServerProcess-2:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 60, in _worker
    remote.send(getattr(env, data))
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function mask_fn at 0x7f98f4f64670>: it's not the same object as __main__.mask_fn
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 60, in _worker
    remote.send(getattr(env, data))
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function mask_fn at 0x7f98f4f64670>: it's not the same object as __main__.mask_fn
Traceback (most recent call last):
  File "test.py", line 98, in <module>
    model.learn(20)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/sb3_contrib/ppo_mask/ppo_mask.py", line 526, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, self.n_steps, use_masking)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/sb3_contrib/ppo_mask/ppo_mask.py", line 289, in collect_rollouts
    if use_masking and not is_masking_supported(env):
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/sb3_contrib/common/maskable/utils.py", line 33, in is_masking_supported
    env.get_attr(EXPECTED_METHOD_NAME)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 173, in get_attr
    return [remote.recv() for remote in target_remotes]
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 173, in <listcomp>
    return [remote.recv() for remote in target_remotes]
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

### System Info

- OS: Linux-5.15.0-91-generic-x86_64-with-glibc2.17
- Python: 3.8.18
- Stable-Baselines3: 2.2.1
- PyTorch: 2.1.2+cu118
- GPU Enabled: True
- Numpy: 1.24.1
- Cloudpickle: 3.0.0
- Gymnasium: 0.28.1

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by 0Addicted0** [comment]
I checked the document again and found a solution, thanks a lot :) 
[https://sb3-contrib.readthedocs.io/en/master/modules/ppo_mask.html#example](url)

**Comment by LYL534** [comment]
I met the similar problem. How can I fix it. This is the error.

Process ForkServerProcess-2:
Process ForkServerProcess-1:
Process ForkServerProcess-3:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
  self.run()
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/process.py", line 108, in run
  self._target(*self._args, **self._kwargs)
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 33, in _worker
  cmd, data = remote.recv()
        ^^^^^^^^^^^^^
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 249, in recv
  buf = self._recv_bytes()
     ^^^^^^^^^^^^^^^^^^
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 413, in _recv_bytes
  buf = self._recv(4)
     ^^^^^^^^^^^^^
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 378, in _recv
  chunk = read(handle, remaining)
      ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
  self.run()
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/process.py", line 108, in run
  self._target(*self._args, **self._kwargs)
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 33, in _worker
  cmd, data = remote.recv()
        ^^^^^^^^^^^^^
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 249, in recv
  buf = self._recv_bytes()
     ^^^^^^^^^^^^^^^^^^
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 413, in _recv_bytes
  buf = self._recv(4)
     ^^^^^^^^^^^^^
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 378, in _recv
  chunk = read(handle, remaining)
      ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
  self.run()
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/process.py", line 108, in run
  self._target(*self._args, **self._kwargs)
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 33, in _worker
  cmd, data = remote.recv()
        ^^^^^^^^^^^^^
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 249, in recv
  buf = self._recv_bytes()
     ^^^^^^^^^^^^^^^^^^
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 413, in _recv_bytes
  buf = self._recv(4)
     ^^^^^^^^^^^^^
 File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 378, in _recv
  chunk = read(handle, remaining)
      ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
./wandb_server.sh: line 12: 142015 Terminated

**Comment by 0Addicted0** [comment]
> I met the similar problem. How can I fix it. This is the error.
> 
> Process ForkServerProcess-2: Process ForkServerProcess-1: Process ForkServerProcess-3: Traceback (most recent call last): Traceback (most recent call last): Traceback (most recent call last): File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap self.run() File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 33, in _worker cmd, data = remote.recv() ^^^^^^^^^^^^^ File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 249, in recv buf = self._recv_bytes() ^^^^^^^^^^^^^^^^^^ File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 413, in _recv_bytes buf = self._recv(4) ^^^^^^^^^^^^^ File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 378, in _recv chunk = read(handle, remaining) ^^^^^^^^^^^^^^^^^^^^^^^ ConnectionResetError: [Errno 104] Connection reset by peer File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap self.run() File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 33, in _worker cmd, data = remote.recv() ^^^^^^^^^^^^^ File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 249, in recv buf = self._recv_bytes() ^^^^^^^^^^^^^^^^^^ File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 413, in _recv_bytes buf = self._recv(4) ^^^^^^^^^^^^^ File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 378, in _recv chunk = read(handle, remaining) ^^^^^^^^^^^^^^^^^^^^^^^ ConnectionResetError: [Errno 104] Connection reset by peer File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap self.run() File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs) File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 33, in _worker cmd, data = remote.recv() ^^^^^^^^^^^^^ File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 249, in recv buf = self._recv_bytes() ^^^^^^^^^^^^^^^^^^ File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 413, in _recv_bytes buf = self._recv(4) ^^^^^^^^^^^^^ File "/home/ma310272/anaconda3/envs/pybamm_env/lib/python3.11/multiprocessing/connection.py", line 378, in _recv chunk = read(handle, remaining) ^^^^^^^^^^^^^^^^^^^^^^^ ConnectionResetError: [Errno 104] Connection reset by peer ./wandb_server.sh: line 12: 142015 Terminated

Hello, with this log alone, I can't figure out why the error occurred. I recommend you read the example above [[https://sb3-contrib.readthedocs.io/en/master/modules/ppo_mask.html#example](https://github.com/DLR-RM/stable-baselines3/issues/url)](url)

**Comment by mwalidcharrwi** [comment]
Hi @0Addicted0 , the link you provided above has No results matched. Can you please double check and share that maskable custom env example again please?

**Comment by 0Addicted0** [comment]
> Hi @0Addicted0 , the link you provided above has No results matched. Can you please double check and share that maskable custom env example again please?

sorry, a bit of bussy, I copy the link into my browser, it works :)   Github modified the jumping process o.O?)

**Comment by mwalidcharrwi** [comment]
> > Hi @0Addicted0 , the link you provided above has No results matched. Can you please double check and share that maskable custom env example again please?
> 
> sorry, a bit of bussy, I copy the link into my browser, it works :) Github modified the jumping process o.O?)

Got it, thanks for the assistance.
