### ISSUE TITLE
[Bug]: IndexError when using HerReplayBuffer

### ISSUE THREAD

**Issue by JonaSi754** [DLR-RM/stable-baselines3#1807]
### 🐛 Bug

I want to use HER to deal with a multi-objective problem, so I implemented the GoalEnv and begin a HER_DDPG training according to the document. But I encountered a IndexError, here is the trace:
```
Traceback (most recent call last):
  File "/home/sssjh/Workspace/MyRL/code/algo/HER_DDPG_task.py", line 29, in <module>
    obs = env.reset()
  File "/home/sssjh/miniconda3/envs/SB3/lib/python3.9/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 75, in reset
    self._save_obs(env_idx, obs)
  File "/home/sssjh/miniconda3/envs/SB3/lib/python3.9/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 107, in _save_obs
    self.buf_obs[key][env_idx] = obs[key]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
My observation space is Dict according to GoalEnv:
```
self.observation_space = spaces.Dict(
        {
            "observation": spaces.Box(low=0, high=1, shape=self.observation_shape),
            "desired_goal": spaces.Box(low=0, high=10000, shape=self.goal_shape),
            "achieved_goal": spaces.Box(low=0, high=10000, shape=self.goal_shape)
        }    
)
```
My usage is like:
```
model = DDPG(
    'MultiInputPolicy', 
    env,
    learning_rate=cfg.lr,
    device=cfg.device,
    replay_buffer_class=HerReplayBuffer,
    replay_buffer_kwargs=dict(
        n_sampled_goal=4,
        goal_selection_strategy=goal_selection_strategy
    ),
    verbose=1
)

model.learn(2000)
```
So I wonder if I miss some important step when using HER? And I also hope the document about HER can be more specific, because really few GoalEnv examples can be found on Google.

Forget to mention my versions: `gym==0.21.0`, and `stable-baselines3==1.8.0`

### To Reproduce

env:
```env

import numpy as np
import gym
from gym import spaces

class env(gym.GoalEnv):

    metadata = {'render.modes': ['human']}
    
    def __init__(self, instance) -> str:
        super(env, self).__init__()
        self.action_shape = (5,)
        self.action_space = spaces.Box(low=-1, high=1, shape=self.action_shape)
        self.observation_shape = (9,)
        self.goal_shape = (4,)
        self.observation_space = spaces.Dict(
            {
                "observation": spaces.Box(low=0, high=1, shape=self.observation_shape),
                "desired_goal": spaces.Box(low=0, high=10000, shape=self.goal_shape),
                "achieved_goal": spaces.Box(low=0, high=10000, shape=self.goal_shape)
            }    
        )

    def reset(self):
        self.states = states(self.Jobs)
        self.done = False
        self.state = np.zeros(self.observation_shape, dtype=np.float32)
        self.goal_state = self.states.observe_goals(self.Jobs)
        return self.state
    
    def render(self, mode='human'):
        pass
    
    def close(self):
        pass
    
    def step(self, action):
        # update state
        self.update_state()
        
        # Give a reward
        desired_goal = self.goal_state
        achieved_goal = self.states.observe_goals()
        reward = self.compute_reward(achieved_goal, desired_goal, {})
        self.goal_state = achieved_goal
            
        # update the observation space
        self.observation_space["observation"] = self.state

        # Record extra information of this step
        info = {
            "observation": self.observation_space
        }
        
        return self.state, reward, self.done, info
```
training:
```training

import numpy as np
import gym
from envs.JSP_v5_goal import env
from stable_baselines3 import HerReplayBuffer
from stable_baselines3.her import GoalSelectionStrategy
from stable_baselines3.ddpg.ddpg import DDPG

env = env("ta21")
obs = env.reset()

cfg = get_args(env)
goal_selection_strategy = GoalSelectionStrategy.FUTURE

model = DDPG(
    'MultiInputPolicy', 
    env,
    learning_rate=cfg.lr,
    device=cfg.device,
    replay_buffer_class=HerReplayBuffer,
    replay_buffer_kwargs=dict(
        n_sampled_goal=4,
        goal_selection_strategy=goal_selection_strategy
    ),
    verbose=1
)

for ep in range(cfg.n_sample):
    model.learn(total_timesteps=cfg.n_epochs * cfg.n_steps)
```

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "/home/sssjh/Workspace/MyRL/code/algo/HER_DDPG_task.py", line 29, in <module>
    obs = env.reset()
  File "/home/sssjh/miniconda3/envs/SB3/lib/python3.9/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 75, in reset
    self._save_obs(env_idx, obs)
  File "/home/sssjh/miniconda3/envs/SB3/lib/python3.9/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 107, in _save_obs
    self.buf_obs[key][env_idx] = obs[key]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

### System Info

- OS: Linux-5.15.0-50-generic-x86_64-with-glibc2.31 # 56~20.04.1-Ubuntu SMP Tue Sep 27 15:51:29 UTC 2022
- Python: 3.9.13
- Stable-Baselines3: 1.8.0
- PyTorch: 2.1.2+cu121
- GPU Enabled: False
- Numpy: 1.23.3
- Gym: 0.21.0

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> My issue does not relate to a custom gym environment. (Use the custom gym env template instead)

try again...

Please use latest SB3 version and check your env using the env checker.
