### ISSUE TITLE
[Bug]: Load a PPO model and re-start learning

### ISSUE THREAD

**Issue by nrigol** [DLR-RM/stable-baselines3#1974]
### 🐛 Bug

I cannot re-start training from a previously trained agent. What am I missing ?

### To Reproduce

```python
import gymnasium as gym

from stable_baselines3 import PPO
from stable_baselines3.common.env_util import make_vec_env

# Parallel environments
vec_env = make_vec_env("CartPole-v1", n_envs=4)

model = PPO("MlpPolicy", vec_env, verbose=1)
model.learn(total_timesteps=25000)
model.save("ppo_cartpole")

del model # remove to demonstrate saving and loading

model = PPO.load("ppo_cartpole", print_system_info=True)

# RE-Train the agent
model.learn(total_timesteps=int(1e4))

```

### Relevant log output / Error message

```shell
== CURRENT SYSTEM INFO ==
- OS: macOS-14.1-arm64-arm-64bit Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:31 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8112
- Python: 3.11.3
- Stable-Baselines3: 2.4.0a5
- PyTorch: 2.2.2
- GPU Enabled: False
- Numpy: 1.25.2
- Cloudpickle: 3.0.0
- Gymnasium: 0.29.1

== SAVED MODEL SYSTEM INFO ==
- OS: macOS-14.1-arm64-arm-64bit Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:31 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8112
- Python: 3.11.3
- Stable-Baselines3: 2.4.0a5
- PyTorch: 2.2.2
- GPU Enabled: False
- Numpy: 1.25.2
- Cloudpickle: 3.0.0
- Gymnasium: 0.29.1

True [[ 0.05495464  0.34424356  0.02004744 -0.24249266]
 [ 0.48956499  0.76959056  0.01912291 -0.36069912]
 [-0.4376061   0.17306022  0.05291673 -0.40955266]
 [-1.5041878  -1.2589557  -0.17553496 -0.28225437]] None
Traceback (most recent call last):
  File "/Users/../cartp.py", line 18, in <module>
    model.learn(total_timesteps=int(1e4))
  File "/opt/homebrew/lib/python3.11/site-packages/stable_baselines3/ppo/ppo.py", line 311, in learn
    return super().learn(
           ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 287, in learn
    total_timesteps, callback = self._setup_learn(
                                ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/stable_baselines3/common/base_class.py", line 423, in _setup_learn
    assert self.env is not None
           ^^^^^^^^^^^^^^^^^^^^
AssertionError
```

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by nrigol** [comment]
model = PPO.load("ppo_cartpole", print_system_info=True)
# ADD THIS
model.env = vec_env
# RE-Train the agent
model.learn(total_timesteps=int(1e4))
