### ISSUE TITLE
[Bug] importing stable baselines 3 on linux and windows directory issue

### ISSUE THREAD

**Issue by Feelfeel20088** [DLR-RM/stable-baselines3#2034]
### 🐛 Bug

Hello, I was packaging stable_baselines3 for NixOS because there is currently no package for it. After successfully fetching the source, I encountered the error below when importing it. It seems to be a directory issue, but I’m not entirely sure. I then also tried to install it on my Windows computer with pip and got a similar error. The error below was on my Windows computer. I have verified that the stable_baselines3 library and Python files are present.

Thank you in advance for your help—I hope this is just a simple mistake on my part.

### To Reproduce

pip install stable_baselines3[extra]

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "c:\Users\trash\OneDrive\Desktop\stuff\RL\snake.py", line 2, in <module>
    import stable_baselines3
  File "C:\Users\trash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\stable_baselines3\__init__.py", line 3, in <module>
    from stable_baselines3.a2c import A2C
  File "C:\Users\trash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\stable_baselines3\a2c\__init__.py", line 1, in <module>
    from stable_baselines3.a2c.a2c import A2C
  File "C:\Users\trash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\stable_baselines3\a2c\a2c.py", line 7, in <module>
    from stable_baselines3.common.buffers import RolloutBuffer
  File "C:\Users\trash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\stable_baselines3\common\buffers.py", line 17, in <module>
    from stable_baselines3.common.vec_env import VecNormalize
  File "C:\Users\trash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\stable_baselines3\common\vec_env\__init__.py", line 14, in <module>
    from stable_baselines3.common.vec_env.vec_video_recorder import VecVideoRecorder
  File "C:\Users\trash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\stable_baselines3\common\vec_env\vec_video_recorder.py", line 4, in <module>
```

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
Could you please give the full traceback? (There is no error name currently)

**Comment by Feelfeel20088** [comment]
sorry about that. When i get home ill get the trace.
