### ISSUE TITLE
[Bug]: Error on utils.get_system_info

### ISSUE THREAD

**Issue by itwasabhi** [DLR-RM/stable-baselines3#2053]
### 🐛 Bug

Calling `utils.get_system_info` tries to check the open-ai gym version. Somehow the open-ai gym import succeeds, but the `__version__` attribute does not exist. 

My hunch is that this is an error in the python env setup and not the underlying code, but I'm not sure how given the env is managed through poetry. 

### To Reproduce

```python
import stable_baselines3 as sb3; 
sb3.get_system_info()
```

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "/home/abhishek/dev/scrappy/scrappy/run_sb3.py", line 3, in <module>
    get_system_info()
  File "/home/abhishek/dev/stable-baselines3/stable_baselines3/common/utils.py", line 547, in get_system_info
    env_info.update({"OpenAI Gym": openai_gym.__version__})
                                   ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'gym' has no attribute '__version__'
```
```


### System Info

```
- OS: Linux-6.8.0-49-generic-x86_64-with-glibc2.39 # 49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024
- Python: 3.12.3
- Stable-Baselines3: 2.5.0a0
- PyTorch: 2.5.1+cu124
- GPU Enabled: True
- Numpy: 2.1.3
- Cloudpickle: 3.1.0
- Gymnasium: 1.0.0
```

### Checklist

- [X] My issue does not relate to a custom gym environment. (Use the custom gym env template instead)
- [X] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo
- [X] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by itwasabhi** [comment]
I do not:
```
abhishek@dcs34445:~/dev/scrappy$ poetry show gym

Package gym not found
abhishek@dcs34445:~/dev/scrappy$ 
abhishek@dcs34445:~/dev/scrappy$ pip show gym
WARNING: Package(s) not found: gym
abhishek@dcs34445:~/dev/scrappy$ ls -d */ | grep "gym"
```

**Comment by qgallouedec** [comment]
What's the output of 

```python
import gym
print(gym.__file__)
```

**Comment by itwasabhi** [comment]
Ahh -- after inspecting `gym.__path__` I see its pointing do a different module I had in my environment of the same name :( 

So no issues here. sorry for the trouble.
