### ISSUE TITLE
Hyperparameter tuning with custom env

### ISSUE THREAD

**Issue by drose188** [DLR-RM/stable-baselines3#275]
Hello,
I am trying to optimize hyperparameters for a custom env with rl-baselines-zoo.
I registered my env and instantiate it. 
I am using this code:

https://github.com/optuna/optuna/blob/master/examples/rl/sb3_simple.py

I get an error in:

stable_baselines3\common\base_class.py", line 385, in _update_info_buffer
    maybe_ep_info = info.get("episode")

AttributeError: 'NoneType' object has no attribute 'get'

[W 2020-12-27 15:41:57,753] Trial 2 failed because of the following error: AttributeError("'NoneType' object has no attribute 'get'",)

What am I missing? Do I have to return specific info from the step?

**Comment by Miffyli** [comment]
Your environment might be returning `None` instead of an empty dictionary. Check docs on [creating custom envs](https://stable-baselines3.readthedocs.io/en/master/guide/custom_env.html) (especially the `check_env` function).

**Comment by drose188** [comment]
It does not seem to be the problem. I printed the dictionary on each step and it is not None and not empty. 
I believe that this error happens at the end of the first trial:


[I 2021-01-04 21:29:25,305] Trial 0 finished with value: -5.244170665740967 and parameters: {'gamma': 0.99, 'lr': 0.005541161985208795, 'batch_size': 128, 'buffer_size': 1000000, 'learning_starts': 10000, 'train_freq': 64, 'tau': 0.05, 'net_arch': 'xlarge'}. Best is trial 0 with value: -5.244170665740967.
Traceback (most recent call last):

  File "E:\QuantConnect\my-algos\rl-forex\optimize - sb3.py", line 267, in <module>
    study.optimize(objective, n_trials=N_TRIALS, n_jobs=N_JOBS, timeout=600)

  File "C:\Users\mypc\Anaconda3\lib\site-packages\optuna\study.py", line 315, in optimize
    show_progress_bar=show_progress_bar,

  File "C:\Users\mypc\Anaconda3\lib\site-packages\optuna\_optimize.py", line 114, in _optimize
    for _ in _iter

  File "C:\Users\mypc\AppData\Roaming\Python\Python36\site-packages\joblib\parallel.py", line 1042, in __call__
    self.retrieve()

  File "C:\Users\mypc\AppData\Roaming\Python\Python36\site-packages\joblib\parallel.py", line 921, in retrieve
    self._output.extend(job.get(timeout=self.timeout))

  File "C:\Users\mypc\Anaconda3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value

  File "C:\Users\mypc\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))

  File "C:\Users\mypc\AppData\Roaming\Python\Python36\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)

  File "C:\Users\mypc\AppData\Roaming\Python\Python36\site-packages\joblib\parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]

  File "C:\Users\mypc\AppData\Roaming\Python\Python36\site-packages\joblib\parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]

  File "C:\Users\mypc\Anaconda3\lib\site-packages\optuna\_optimize.py", line 156, in _optimize_sequential
    trial = _run_trial(study, func, catch)

  File "C:\Users\mypc\Anaconda3\lib\site-packages\optuna\_optimize.py", line 189, in _run_trial
    value = func(trial)

  File "E:\QuantConnect\my-algos\rl-forex\optimize - sb3.py", line 237, in objective
    model.learn(N_TIMESTEPS, callback=eval_callback)

  File "C:\Users\mypc\Anaconda3\lib\site-packages\stable_baselines3\sac\sac.py", line 293, in learn
    reset_num_timesteps=reset_num_timesteps,

  File "C:\Users\mypc\Anaconda3\lib\site-packages\stable_baselines3\common\off_policy_algorithm.py", line 259, in learn
    log_interval=log_interval,

  File "C:\Users\mypc\Anaconda3\lib\site-packages\stable_baselines3\common\off_policy_algorithm.py", line 424, in collect_rollouts
    self._update_info_buffer(infos, done)

  File "C:\Users\mypc\Anaconda3\lib\site-packages\stable_baselines3\common\base_class.py", line 385, in _update_info_buffer
    maybe_ep_info = info.get("episode")

AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Miffyli** [comment]
I'd still run the environment through `check_env` as the error seems to be purely related to stable-baselines3 and/or the environment, not zoo itself. Also try running your environment with stable-baselines3 directly without hyperparameter optimization and such (e.g. `A2C("MlpPolicy", your_env).learn(10000)`).
