### ISSUE TITLE
KeyError: 'observation' while running gym

### ISSUE THREAD

**Issue by Mahesha999** [DLR-RM/stable-baselines3#357]
I was trying to use hungry-geese gym [here](https://www.kaggle.com/victordelafuente/dqn-goose-with-stable-baselines3-pytorch#) to train PPO. But my game was getting played for only one step. After running with debug ON I got following trace:

    Traceback (most recent call last):
      File "c:\users\crrma\.virtualenvs\hungry_geese-ept5y6nv\lib\site-packages\kaggle_environments\agent.py", line 151, in act
        action = self.agent(*args)
      File "<ipython-input-29-faad97d317d6>", line 5, in agent_ppo
        a = directions[loaded_model.predict(obs)[0]]
      File "c:\users\crrma\.virtualenvs\hungry_geese-ept5y6nv\lib\site-packages\stable_baselines3\common\base_class.py", line 497, in predict
        return self.policy.predict(observation, state, mask, deterministic)
      File "c:\users\crrma\.virtualenvs\hungry_geese-ept5y6nv\lib\site-packages\stable_baselines3\common\policies.py", line 262, in predict
        observation = ObsDictWrapper.convert_dict(observation)
      File "c:\users\crrma\.virtualenvs\hungry_geese-ept5y6nv\lib\site-packages\stable_baselines3\common\vec_env\obs_dict_wrapper.py", line 68, in convert_dict
        return np.concatenate([observation_dict[observation_key], observation_dict[goal_key]], axis=-1)
    KeyError: 'observation'

So I debuged a bit more in vscode. As can be seen in below screenshot, both `observation` and `desired_goal` keys are not present in `observation_dict`. 

![image](https://user-images.githubusercontent.com/4706946/111796602-55528f00-88ee-11eb-9a82-7e663f4e37b4.png)

Also this is how I debuged to above call:

![image](https://user-images.githubusercontent.com/4706946/111797039-c7c36f00-88ee-11eb-89ce-7bfd4e703e0b.png)

Am I using API incorrectly for this to occur (am new to the API)? (or this can be a bug, which I feel highly unlikely.)

[Colab notebook](https://drive.google.com/file/d/12g6Xzd2s2SlXYjjGYcgKvUgRWyVRF1rY/view?usp=sharing) and [model](https://drive.google.com/drive/folders/12jEUfepauRhsVRPvqZ61C25GVd1kTZUd?usp=sharing)

**Comment by araffin** [comment]
Hello,
Please use the custom gym env template.
Dictionary observations are currently not supported (cf. docs) expect for HER+offpolicy algorithms.

However, you can use this branch: https://github.com/DLR-RM/stable-baselines3/pull/243
(this adds proprer support to all algorithms) or flatten the observation using a [gym wrapper](https://github.com/openai/gym/blob/master/gym/wrappers/flatten_observation.py).

**Comment by Mahesha999** [comment]
I dont know if I got you correct.
I used custom gym env for learning model. 
Do you mean to say I should also use same custom environment instead of kaggle environment (to run game against others agent)? 
From `agent_ppo()` method, I am returning action returned by `predict()` of learned model, as required by kaggle environment for running multi agent game. So am guessing how it is possible to use gym environment instead of kaggle environment to run a game.

I tried did `pipenv install git+https://github.com/J-Travnik/stable-baselines3.git@feat/dict_observations#egg=stable_baselines3` and then tried the same code and now getting following:

```
Traceback (most recent call last):
  File "c:\users\crrma\.virtualenvs\hungry_geese_keyerr-wux_fjav\lib\site-packages\kaggle_environments\agent.py", line 151, in act
    action = self.agent(*args)
  File "<ipython-input-5-b7e487a6d4fb>", line 5, in agent_ppo
    a = directions[loaded_model.predict(obs)[0]]
  File "c:\users\crrma\.virtualenvs\hungry_geese_keyerr-wux_fjav\lib\site-packages\stable_baselines3\common\base_class.py", line 509, in predict
    return self.policy.predict(observation, state, mask, deterministic)
  File "c:\users\crrma\.virtualenvs\hungry_geese_keyerr-wux_fjav\lib\site-packages\stable_baselines3\common\policies.py", line 280, in predict
    obs_space = self.observation_space.spaces[key]
AttributeError: 'Box' object has no attribute 'spaces'
```

**Comment by araffin** [comment]
i meant the custom env issue template

**Comment by notshashwat** [comment]
> Hello, Please use the custom gym env template. Dictionary observations are currently not supported (cf. docs) except for HER+offpolicy algorithms (and for GoalEnv only).
 
Is it still not supported ?
