### ISSUE TITLE
[Bug] AttributeError: 'DummyVecEnv' object has no attribute 'obs_dim'

### ISSUE THREAD

**Issue by tom-doerr** [DLR-RM/stable-baselines3#377]
### 🐛 Bug
I'm getting an AttributeError even though this example is very similar to the one on the GitHub page. 

### To Reproduce

```python
import gym

from stable_baselines3 import HER, SAC

env = gym.make("CarRacing-v0")

model = HER("CnnPolicy", env, model_class=SAC, verbose=1)
model.learn(total_timesteps=10000)

obs = env.reset()
for i in range(1000):
    action, _states = model.predict(obs, deterministic=True)
    obs, reward, done, info = env.step(action)
    env.render()
    if done:
      obs = env.reset()

env.close()

```

```bash
➜  stable-baselines3 git:(fix_extra_install_command) ✗ ./test.py 
WARNING: CPU random generator seem to be failing, disabling hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
WARNING: CPU random generator seem to be failing, disable hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
/home/tom/.local/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Using cuda device
Traceback (most recent call last):
  File "./test.py", line 8, in <module>
    model = HER("CnnPolicy", env, model_class=SAC, verbose=1)
  File "/home/tom/git/stable-baselines3/stable_baselines3/her/her.py", line 140, in __init__
    self._episode_storage = HerReplayBuffer(
  File "/home/tom/git/stable-baselines3/stable_baselines3/her/her_replay_buffer.py", line 62, in __init__
    "observation": (self.env.num_envs, self.env.obs_dim),
  File "/home/tom/git/stable-baselines3/stable_baselines3/common/vec_env/base_vec_env.py", line 313, in __getattr__
    return self.getattr_recursive(name)
  File "/home/tom/git/stable-baselines3/stable_baselines3/common/vec_env/base_vec_env.py", line 338, in getattr_recursive
    attr = getattr(self.venv, name)
AttributeError: 'DummyVecEnv' object has no attribute 'obs_dim'
```

### System Info
Gym: 0.18.0
Python: 3.8.5
stable-baselines3: 1.0

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [ ] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment]
> I have read the documentation (required)

...

from the documentation:
"
HER requires the environment to inherits from gym.GoalEnv
"

I would recommend you reading more about the HER algorithm, it cannot be applied to any problem.
