### ISSUE TITLE
PPO + gSDE trained on GPU thow an error at test time with `deterministic=True`

### ISSUE THREAD

**Issue by araffin** [DLR-RM/stable-baselines3#44]
**Describe the bug**

See issue https://github.com/DLR-RM/rl-baselines3-zoo/issues/18

**Code example**
Please try to provide a minimal example to reproduce the bug. Error messages and stack traces are also helpful.

Please use the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)
for both code and stack traces.

```python
python train.py --algo ppo --env AntBulletEnv-v0 -n 1000 -params use_sde:True
python enjoy.py --algo ppo --env AntBulletEnv-v0 -f logs --no-render
```

```bash
Traceback (most recent call last):
  File "enjoy.py", line 204, in <module>
    main()
  File "enjoy.py", line 131, in main
    action, state = model.predict(obs, state=state, deterministic=deterministic)
  File "/home/dell/stable-baselines3/stable_baselines3/common/base_class.py", line 321, in predict
    return self.policy.predict(observation, state, mask, deterministic)
  File "/home/dell/stable-baselines3/stable_baselines3/common/policies.py", line 225, in predict
    actions = self._predict(observation, deterministic=deterministic)
  File "/home/dell/stable-baselines3/stable_baselines3/ppo/policies.py", line 278, in _predict
    return distribution.get_actions(deterministic=deterministic)
  File "/home/dell/stable-baselines3/stable_baselines3/common/distributions.py", line 59, in get_actions
    return self.sample()
  File "/home/dell/stable-baselines3/stable_baselines3/common/distributions.py", line 551, in sample
    noise = self.get_noise(self._latent_sde)
  File "/home/dell/stable-baselines3/stable_baselines3/common/distributions.py", line 542, in get_noise
    return th.mm(latent_sde, self.exploration_mat)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'mat2' in call to _th_mm


```

**System Info**
Describe the characteristic of your environment:
* latest version (with fix for VecEnv)
* CUDA enabled

**Comment by araffin** [comment]
Same issue with all models, e.g. for SAC:
```
python enjoy.py --algo sac --env AntBulletEnv-v0 -n 1000 --stochastic -f logs
```
