### ISSUE TITLE
[Bug] Bad error message for EvalCallback

### ISSUE THREAD

**Issue by benblack769** [DLR-RM/stable-baselines3#443]
### 🐛 Bug

The following code:

```python
from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import EvalCallback
import gym

env = gym.make("SpaceInvadersNoFrameskip-v4")
eval_env = gym.make("SpaceInvadersNoFrameskip-v4")

model = PPO("CnnPolicy", env, verbose=3, batch_size=64, n_steps=512, gamma=0.99, learning_rate=0.00018085932590331433, ent_coef=0.09728964435428247, clip_range=0.4, n_epochs=10, vf_coef=0.27344752686795376, gae_lambda=0.9, max_grad_norm=5)
eval_callback = EvalCallback(eval_env, best_model_save_path='./logs/', log_path='./logs/', eval_freq=int(1000), deterministic=True, render=False)
model.learn(total_timesteps=4000000, callback=eval_callback)
model.save("policy_optimal")
```

Gives the following error on the master branch of SB3 (gives a similar error in 1.0 release):

```
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.
/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/stable_baselines3/common/callbacks.py:327: UserWarning: Training and eval env are not of the same type<stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object at 0x7fbbe39c9be0> != <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7fbbe39e8400>
  warnings.warn("Training and eval env are not of the same type" f"{self.training_env} != {self.eval_env}")
----------------------------
| time/              |     |
|    fps             | 474 |
|    iterations      | 1   |
|    time_elapsed    | 1   |
|    total_timesteps | 512 |
----------------------------
Traceback (most recent call last):
  File "bad_sb3.py", line 10, in <module>
    model.learn(total_timesteps=4000000, callback=eval_callback)
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/stable_baselines3/ppo/ppo.py", line 302, in learn
    reset_num_timesteps=reset_num_timesteps,
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 235, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 182, in collect_rollouts
    if callback.on_step() is False:
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/stable_baselines3/common/callbacks.py", line 88, in on_step
    return self._on_step()
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/stable_baselines3/common/callbacks.py", line 358, in _on_step
    sync_envs_normalization(self.training_env, self.eval_env)
  File "/home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/stable_baselines3/common/vec_env/__init__.py", line 72, in sync_envs_normalization
    eval_env_tmp = eval_env_tmp.venv
AttributeError: 'DummyVecEnv' object has no attribute 'venv'
```

I know that the [documentation for EvalCallback](https://stable-baselines3.readthedocs.io/en/master/guide/callbacks.html?highlight=EvalCallback#evalcallback) does mention an issue like this, however it is not obvious what the solution is. After much time and effort, we figured out that the solution is to wrap the eval_env in the VecTransposeWrapper. However, this fix is highly non-obvious. 

It would be extremely helpful if both the error message/warning in the code gave a more informative message as to what the fix is, and the documentation has an example of how to use the wrapper in a case with an image observation.

### Checklist

- [ ] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [ ] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [ ] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by benblack769** [comment]
@justinkterry

**Comment by justinkterry** [comment]
I also think that it would be a good idea to add the transpose obs wrapper to the evaluation function since all the policy learning methods appear to have it.

**Comment by araffin** [comment]
Hello,

Although I agree the error is not very informative, there is an explicit warning at the beginning of training ("Training and eval env are not of the same type") and it is also [documented](https://stable-baselines3.readthedocs.io/en/master/guide/callbacks.html#evalcallback).

I would appreciate a PR that solves this issue (probably catching the error and outputting a more informative message), don't forget to follow the contributing guide and add a test.

Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/372 and https://github.com/DLR-RM/stable-baselines3/issues/388 and related to https://github.com/DLR-RM/stable-baselines3/issues/426

**Comment by mud0703** [comment]
As both the Training and eval env are not of the same type , also if you are using the image based environment with observation HxWxC. We need to use vec_transpose to change the order of the HxWxC to CxHxW for eval_env.
```
from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import EvalCallback
from stable_baselines3.common.vec_env import vec_transpose
import gym

env = gym.make("SpaceInvadersNoFrameskip-v4")
eval_env = vec_transpose.VecTransposeImage(env)

model = PPO("CnnPolicy", env, verbose=3, batch_size=64, n_steps=512, gamma=0.99, learning_rate=0.00018085932590331433, ent_coef=0.09728964435428247, clip_range=0.4, n_epochs=10, vf_coef=0.27344752686795376, gae_lambda=0.9, max_grad_norm=5)
eval_callback = EvalCallback(eval_env, best_model_save_path='./logs/', log_path='./logs/', eval_freq=int(1000), deterministic=True, render=False)
model.learn(total_timesteps=4000000, callback=eval_callback)
model.save("policy_optimal")
```
