### ISSUE TITLE
[Bug] exepcion ignored in <function Viewer.__del__ ...

### ISSUE THREAD

**Issue by externalsupplierstaff** [DLR-RM/stable-baselines3#456]
### 🐛 Bug

When using one on the examples on windows I get an error in the very end. It's not important, but I like a clean terminal output.

### To Reproduce

Steps to reproduce the behavior.

```python
import stable_baselines3 as sb3

def run_cartpole_ppo_vec():
    env_id = "CartPole-v1"
    num_cpu = 4  # Number of processes to use
    env = sb3.common.env_util.make_vec_env(env_id, n_envs=num_cpu, seed=0)

    model = sb3.PPO('MlpPolicy', env, verbose=1)
    model.learn(total_timesteps=25000)

    obs = env.reset()
    for _ in range(10):
        action, _states = model.predict(obs)
        obs, rewards, dones, info = env.step(action)
        env.render()

    print('>'*40)
    print("got here")
    print('<'*40)

if __name__ == '__main__':
    run_cartpole_ppo_vec()
```

```bash
(sandbox) PS D:\lalabox\lalacompany\code\exploration\lalapaper> python .\playground.py
Using cpu device
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 21.2     |
|    ep_rew_mean     | 21.2     |
| time/              |          |
|    fps             | 5287     |
|    iterations      | 1        |
|    time_elapsed    | 1        |
|    total_timesteps | 8192     |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 34          |
|    ep_rew_mean          | 34          |
| time/                   |             |
|    fps                  | 2166        |
|    iterations           | 2           |
|    time_elapsed         | 7           |
|    total_timesteps      | 16384       |
| train/                  |             |
|    approx_kl            | 0.015733536 |
|    clip_fraction        | 0.229       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.681      |
|    explained_variance   | 0.000331    |
|    learning_rate        | 0.0003      |
|    loss                 | 4.55        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0254     |
|    value_loss           | 18.6        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 69.3        |
|    ep_rew_mean          | 69.3        |
| time/                   |             |
|    fps                  | 1833        |
|    iterations           | 3           |
|    time_elapsed         | 13          |
|    total_timesteps      | 24576       |
| train/                  |             |
|    approx_kl            | 0.017395234 |
|    clip_fraction        | 0.19        |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.645      |
|    explained_variance   | 0.416       |
|    learning_rate        | 0.0003      |
|    loss                 | 11.6        |
|    n_updates            | 20          |
|    policy_gradient_loss | -0.0344     |
|    value_loss           | 24.9        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 101         |
|    ep_rew_mean          | 101         |
| time/                   |             |
|    fps                  | 1693        |
|    iterations           | 4           |
|    time_elapsed         | 19          |
|    total_timesteps      | 32768       |
| train/                  |             |
|    approx_kl            | 0.015109017 |
|    clip_fraction        | 0.18        |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.602      |
|    explained_variance   | 0.452       |
|    learning_rate        | 0.0003      |
|    loss                 | 20.4        |
|    n_updates            | 30          |
|    policy_gradient_loss | -0.0291     |
|    value_loss           | 38.4        |
-----------------------------------------
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
got here
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Exception ignored in: <function Viewer.__del__ at 0x000001A49DEEC9D0>
Traceback (most recent call last):
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\site-packages\gym\envs\classic_control\rendering.py", line 165, in __del__
    self.close()
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\site-packages\gym\envs\classic_control\rendering.py", line 83, in close
    self.window.close()
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\site-packages\pyglet\window\win32\__init__.py", line 319, in close
    super(Win32Window, self).close()
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\site-packages\pyglet\window\__init__.py", line 838, in close
    app.windows.remove(self)
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\_weakrefset.py", line 109,
in remove
    self.data.remove(ref(item))
KeyError: <weakref at 0x000001A49DEA3090; to 'Win32Window' at 0x000001A4A3BE8F70>
Exception ignored in: <function Viewer.__del__ at 0x000001A49DEEC9D0>
Traceback (most recent call last):
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\site-packages\gym\envs\classic_control\rendering.py", line 165, in __del__
    self.close()
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\site-packages\gym\envs\classic_control\rendering.py", line 83, in close
    self.window.close()
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\site-packages\pyglet\window\win32\__init__.py", line 319, in close
    super(Win32Window, self).close()
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\site-packages\pyglet\window\__init__.py", line 838, in close
    app.windows.remove(self)
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\_weakrefset.py", line 109,
in remove
    self.data.remove(ref(item))
KeyError: <weakref at 0x000001A49DEA3090; to 'Win32Window' at 0x000001A4AD3C12E0>
Exception ignored in: <function Viewer.__del__ at 0x000001A49DEEC9D0>
Traceback (most recent call last):
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\site-packages\gym\envs\classic_control\rendering.py", line 165, in __del__
    self.close()
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\site-packages\gym\envs\classic_control\rendering.py", line 83, in close
    self.window.close()
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\site-packages\pyglet\window\win32\__init__.py", line 319, in close
    super(Win32Window, self).close()
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\site-packages\pyglet\window\__init__.py", line 838, in close
    app.windows.remove(self)
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\_weakrefset.py", line 109,
in remove
    self.data.remove(ref(item))
KeyError: <weakref at 0x000001A4AD5D5DB0; to 'Win32Window' at 0x000001A4AD5BB7C0>
Exception ignored in: <function Viewer.__del__ at 0x000001A49DEEC9D0>
Traceback (most recent call last):
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\site-packages\gym\envs\classic_control\rendering.py", line 165, in __del__
    self.close()
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\site-packages\gym\envs\classic_control\rendering.py", line 83, in close
    self.window.close()
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\site-packages\pyglet\window\win32\__init__.py", line 319, in close
    super(Win32Window, self).close()
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\site-packages\pyglet\window\__init__.py", line 838, in close
    app.windows.remove(self)
  File "C:\Users\usern\Miniconda3.9\envs\sandbox\lib\_weakrefset.py", line 109,
in remove
    self.data.remove(ref(item))
KeyError: <weakref at 0x000001A4AD5D5DB0; to 'Win32Window' at 0x000001A4AD616100>
(sandbox) PS D:\lalabox\lalacompany\code\exploration\lalapaper>

```

### Expected behavior

Get the exact same output until <<<<<<<<<<<

### System Info

Describe the characteristic of your environment:
 * Describe how the library was installed (pip, docker, source, ...)
 conda virtual environment
 * GPU models and configuration
 no gpu
 * Python version
 3.8.10
 * PyTorch version
 1.8.1
 * Gym version
 0.18.0
 * Versions of any other relevant libraries
```bash
#
# Name                    Version                   Build  Channel
absl-py                   0.12.0             pyhd8ed1ab_0    conda-forge
affine                    2.3.0                    pypi_0    pypi
aiohttp                   3.7.4            py38h294d835_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
astroid                   2.5              py38haa95532_1
async-timeout             3.0.1                   py_1000    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
black                     19.10b0                    py_0
blas                      1.0                         mkl
blinker                   1.4                        py_1    conda-forge
blosc                     1.21.0               h0e60522_0    conda-forge
boost-cpp                 1.74.0               h54f0996_1    conda-forge
brotli                    1.0.9                h0e60522_4    conda-forge
brotlipy                  0.7.0           py38h294d835_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cachetools                4.2.2              pyhd8ed1ab_0    conda-forge
certifi                   2020.12.5        py38haa244fe_1    conda-forge
cffi                      1.14.5           py38hd8c33c5_0    conda-forge
chardet                   4.0.0            py38haa244fe_1    conda-forge
charls                    2.2.0                h39d44d4_0    conda-forge
click                     7.1.2                    pypi_0    pypi
click-plugins             1.1.1                    pypi_0    pypi
cligj                     0.7.1                    pypi_0    pypi
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
colorio                   0.7.3                    pypi_0    pypi
colour-science            0.3.16             pyh44b312d_1    conda-forge
cpuonly                   1.0                           0    pytorch
cryptography              3.4.7            py38hd7da0ea_0    conda-forge
curl                      7.68.0               h4496350_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py38h294d835_3    conda-forge
dask-core                 2021.5.0           pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_1    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
exifread                  2.1.2                      py_1    conda-forge
expat                     2.3.0                h39d44d4_0    conda-forge
ffmpeg                    4.3.1                ha925a31_0    conda-forge
fftw                      3.3.9           nompi_hd3ad3c4_101    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
fsspec                    2021.5.0           pyhd8ed1ab_0    conda-forge
future                    0.18.2           py38haa244fe_3    conda-forge
gdal                      2.3.3            py38hdf43c64_0
geos                      3.7.1                h33f27b4_0
giflib                    5.2.1                h8d14728_2    conda-forge
google-auth               1.30.0             pyh44b312d_0    conda-forge
google-auth-oauthlib      0.4.1                      py_2    conda-forge
grpcio                    1.37.1           py38he5377a8_0    conda-forge
gym                       0.18.0           py38h43734a8_1    conda-forge
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.4          nompi_hcc15c50_1106    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagecodecs               2021.3.31        py38h5da4933_0
imageio                   2.9.0                      py_0    conda-forge
importlib-metadata        4.0.1            py38haa244fe_0    conda-forge
intel-openmp              2021.2.0           h57928b3_616    conda-forge
ipykernel                 5.3.4            py38h5ca1d4c_0
ipython                   7.23.1           py38h43734a8_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.8.0              pyhd8ed1ab_0    conda-forge
jedi                      0.18.0           py38haa244fe_2    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9b                   hb83a4c4_2
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py38haa244fe_0    conda-forge
kealib                    1.4.7                h07cbb95_6
kiwisolver                1.3.1            py38hbd9d945_1    conda-forge
krb5                      1.16.4               hdd46e55_0    conda-forge
lazy-object-proxy         1.6.0            py38h294d835_0    conda-forge
lcms2                     2.12                 h83e58a3_0
lerc                      2.2.1                h0e60522_0    conda-forge
libaec                    1.0.4                h39d44d4_1    conda-forge
libcurl                   7.68.0               h4496350_0    conda-forge
libdeflate                1.7                  h8ffe710_5    conda-forge
libgdal                   2.3.3                h10f50ba_0
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h9859afa_1013    conda-forge
libnetcdf                 4.6.1                h411e497_2
libopencv                 4.0.1                hbb9e17c_0
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     11.5                 hb0bdaea_2    conda-forge
libprotobuf               3.17.0               h7755175_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialite             4.3.0a            h6a0152f_1026    conda-forge
libssh2                   1.9.0                h680486a_6    conda-forge
libtiff                   4.2.0                hd0e1b90_0
libuv                     1.41.0               h8ffe710_0    conda-forge
libxml2                   2.9.12               hf5bbc77_0    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
llvmlite                  0.36.0           py38h57a6900_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge
markdown                  3.3.4              pyhd8ed1ab_0    conda-forge
matplotlib                3.3.4            py38haa95532_0
matplotlib-base           3.3.4            py38h34ddff4_0    conda-forge
matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
meshio                    4.4.3                    pypi_0    pypi
meshzoo                   0.7.3                    pypi_0    pypi
mkl                       2021.2.0           haa95532_296
mkl-service               2.3.0            py38h2bbff1b_1
mkl_fft                   1.3.0            py38h277e83a_2
mkl_random                1.2.1            py38hf11a4ad_2
multidict                 5.1.0            py38h294d835_1    conda-forge
mypy_extensions           0.4.3            py38haa244fe_3    conda-forge
networkx                  2.3                        py_0    conda-forge
ninja                     1.10.2               h5362a0b_0    conda-forge
numba                     0.53.1           py38hf11a4ad_0
numpy                     1.20.1           py38h34a8a5c_0
numpy-base                1.20.1           py38haf7ebc8_0
oauthlib                  3.0.1                      py_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv                    4.0.1            py38h2a7c758_0
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1k               h8ffe710_0    conda-forge
pandas                    1.2.4                    pypi_0    pypi
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
pcre                      8.44                 ha925a31_0    conda-forge
phasepack                 1.5                      pypi_0    pypi
pickleshare               0.7.5                   py_1003    conda-forge
piexif                    1.1.3                      py_2    conda-forge
pillow                    8.2.0            py38h4fa10fc_0
pip                       21.1.1             pyhd8ed1ab_0    conda-forge
proj4                     5.2.0             h6538335_1006    conda-forge
prompt-toolkit            3.0.18             pyha770c72_0    conda-forge
protobuf                  3.17.0           py38h885f38d_0    conda-forge
py-opencv                 4.0.1            py38he44ac1e_0
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyfftw                    0.12.0           py38h3dc0267_2    conda-forge
pyglet                    1.5.16           py38haa244fe_0    conda-forge
pygments                  2.9.0              pyhd8ed1ab_0    conda-forge
pygmsh                    7.1.9                    pypi_0    pypi
pyjwt                     2.1.0              pyhd8ed1ab_0    conda-forge
pylibtiff                 0.4.2            py38hdbb2d2f_3    conda-forge
pylint                    2.7.4            py38haa95532_1
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.9.2            py38ha925a31_4
pysocks                   1.7.1            py38haa244fe_3    conda-forge
python                    3.8.10          h7840368_1_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.8.1               py3.8_cpu_0  [cpuonly]  pytorch
pytz                      2021.1                   pypi_0    pypi
pyvista                   0.30.0                   pypi_0    pypi
pywavelets                1.1.1            py38h347fdf6_3    conda-forge
pywin32                   300              py38h294d835_0    conda-forge
pyyaml                    5.4.1            py38h294d835_0    conda-forge
pyzmq                     22.0.3           py38h09162b1_1    conda-forge
qt                        5.9.7            vc14h73c81de_0
rawpy                     0.16.0                   pypi_0    pypi
regex                     2021.4.4         py38h294d835_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
rsa                       4.7.2              pyh44b312d_0    conda-forge
scikit-image              0.18.1           py38hf11a4ad_0
scikit-learn              0.24.1           py38hf11a4ad_0
scipy                     1.6.2            py38h66253e8_1
scooby                    0.5.7                    pypi_0    pypi
setuptools                49.6.0           py38haa244fe_3    conda-forge
sewar                     0.4.4                    pypi_0    pypi
sip                       4.19.13          py38ha925a31_0
six                       1.16.0             pyh6c4a22f_0    conda-forge
sk-video                  1.1.10             pyh24bf2e0_4    conda-forge
snappy                    1.1.8                ha925a31_3    conda-forge
snuggs                    1.4.7                    pypi_0    pypi
sqlite                    3.35.5               h8ffe710_0    conda-forge
stable-baselines3         1.0                      pypi_0    pypi
tbb                       2020.2               h2d74725_4    conda-forge
tensorboard               2.4.1              pyhd8ed1ab_0    conda-forge
tensorboard-plugin-wit    1.8.0              pyh44b312d_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tifffile                  2021.4.8           pyhd8ed1ab_0    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
torch-tb-profiler         0.1.0                    pypi_0    pypi
torchaudio                0.8.1                      py38    pytorch
torchvision               0.9.1                  py38_cpu  [cpuonly]  pytorch
tornado                   6.1              py38h294d835_1    conda-forge
tqdm                      4.59.0             pyhd3eb1b0_1
traitlets                 5.0.5                      py_0    conda-forge
transforms3d              0.3.1                    pypi_0    pypi
typed-ast                 1.4.3            py38h294d835_0    conda-forge
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_4    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_4    conda-forge
vtk                       9.0.1                    pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
werkzeug                  2.0.0              pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
win_inet_pton             1.1.0            py38haa244fe_2    conda-forge
wincertstore              0.2             py38haa244fe_1006    conda-forge
wrapt                     1.12.1           py38h294d835_3    conda-forge
xerces-c                  3.2.3                h0e60522_2    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yarl                      1.6.3            py38h294d835_1    conda-forge
zeromq                    4.3.4                h0e60522_0    conda-forge
zfp                       0.5.5                h0e60522_5    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.5                h04227a9_0
```

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**) (looked for `weakref` without results
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment]
Hello,
You probably to just call `env.close()` at the end (cf. issues on the gym repo).

**Comment by externalsupplierstaff** [comment]
that was it, thanks!
