### ISSUE TITLE
VideoRecorder object has no attribute path

### ISSUE THREAD

**Issue by JimLiu1213** [DLR-RM/stable-baselines3#504]
### Question

I am using video recorder from the stable-baselines3 tutorial on Colab with a custom env
### Additional context
```python

import os
os.system("Xvfb :1 -screen 0 1024x768x24 &")
os.environ['DISPLAY'] = ':1'
import base64
from pathlib import Path

from IPython import display as ipythondisplay

def show_videos(video_path='', prefix=''):
  """
  Taken from https://github.com/eleurent/highway-env

  :param video_path: (str) Path to the folder containing videos
  :param prefix: (str) Filter the video, showing only the only starting with this prefix
  """
  html = []
  for mp4 in Path(video_path).glob("{}*.mp4".format(prefix)):
      video_b64 = base64.b64encode(mp4.read_bytes())
      html.append('''<video alt="{}" autoplay 
                    loop controls style="height: 400px;">
                    <source src="data:video/mp4;base64,{}" type="video/mp4" />
                </video>'''.format(mp4, video_b64.decode('ascii')))
  ipythondisplay.display(ipythondisplay.HTML(data="<br>".join(html)))
from stable_baselines3.common.vec_env import VecVideoRecorder, DummyVecEnv

def record_video(env_id, model, video_length=500, prefix='', video_folder='videos/'):
  """
  :param env_id: (str)
  :param model: (RL model)
  :param video_length: (int)
  :param prefix: (str)
  :param video_folder: (str)
  """
  eval_env = DummyVecEnv([lambda: gym.make(env_id)])
  # Start the video at step=0 and record 500 steps
  eval_env = VecVideoRecorder(eval_env, video_folder=video_folder,
                              record_video_trigger=lambda step: step == 0, video_length=video_length,
                              name_prefix=prefix)

  obs = eval_env.reset()
  for _ in range(video_length):
    action, _ = model.predict(obs)
    obs, _, _, _ = eval_env.step(action)

  # Close the video recorder
  eval_env.close()
```

```
env = DummyVecEnv([lambda: gym.make('FoodHuntingHSR-v1')])
#env = gym.make('FoodHuntingHSR-v1')
model = DDPG.load("saved_model", env=env, verbose=1)
record_video('FoodHuntingHSR-v1', model, video_length=500, prefix='ddpg-food')

```
ERROR:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-15-4f41bee5e37f> in <module>()
----> 1 record_video('FoodHuntingHSR-v1', model, video_length=1000, prefix='ddpg-food')

2 frames
<ipython-input-12-56d16ba8c872> in record_video(env_id, model, video_length, prefix, video_folder)
     21   for _ in range(video_length):
     22     action, _ = model.predict(obs)
---> 23     obs, _, _, _ = eval_env.step(action)
     24 
     25   # Close the video recorder

/content/gdrive/My Drive/hsr/PyLIS/gym-foodhunting/stable-baselines3/stable_baselines3/common/vec_env/base_vec_env.py in step(self, actions)
    160         """
    161         self.step_async(actions)
--> 162         return self.step_wait()
    163 
    164     def get_images(self) -> Sequence[np.ndarray]:

/content/gdrive/My Drive/hsr/PyLIS/gym-foodhunting/stable-baselines3/stable_baselines3/common/vec_env/vec_video_recorder.py in step_wait(self)
     93             self.recorded_frames += 1
     94             if self.recorded_frames > self.video_length:
---> 95                 print(f"Saving video to {self.video_recorder.path}")
     96                 self.close_video_recorder()
     97         elif self._video_enabled():

AttributeError: 'VideoRecorder' object has no attribute 'path'
```
### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,

>I am using video recorder from the stable-baselines3 tutorial on Colab with a custom env

Does it work with a classic gym env? (I guess so because I just checked our [colab tutorial](https://colab.research.google.com/github/araffin/rl-tutorial-jnrr19/blob/sb3/1_getting_started.ipynb))

If so, the issue comes from your custom gym env, and you should fill the custom env issue.
Make sure to correctly implement the `render()` method when `mode="rgb_array"` is passed (you can take a look at gym source code for examples), it must return an image.

**Comment by JimLiu1213** [comment]
This is my env after modified according to your advice, but still:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/gdrive/My Drive/hsr/rl-baselines3-zoo/utils/record_video.py", line 101, in <module>
    env.reset()
  File "/content/gdrive/My Drive/hsr/stable-baselines3/stable_baselines3/common/vec_env/vec_video_recorder.py", line 68, in reset
    self.start_video_recorder()
  File "/content/gdrive/My Drive/hsr/stable-baselines3/stable_baselines3/common/vec_env/vec_video_recorder.py", line 80, in start_video_recorder
    print(self.video_recorder.path)
AttributeError: 'VideoRecorder' object has no attribute 'path'
```
It seemed that the VideoRecorder form gym.wrapper.monitoring was not used, since I tried to print the self.path of the VideoRecorder and nothing showed up. Please, can you give me some hints. It took me so much time. 
```
self.video_recorder = video_recorder.VideoRecorder(
            env=self.env, base_path=base_path, metadata={"step_id": self.step_id}
        )
```

```
class FoodHuntingEnv(gym.Env):
    metadata = {'render.modes': ['human']}

    GRAVITY = -10.0
    BULLET_STEPS = 120 # p.setTimeStep(1.0 / 240.0), so 1 gym step == 0.5 sec.

    def __init__(self, render=False, robot_model=R2D2, max_steps=500, num_foods=3, num_fakes=0, object_size=1.0, object_radius_scale=1.0, object_radius_offset=1.0, object_angle_scale=1.0):
        """Initialize environment.
        """
        ### gym variables
        self.observation_space = robot_model.getObservationSpace() # classmethod
        self.action_space = robot_model.getActionSpace() # classmethod
        self.reward_range = (-1.0, 1.0)
        self.seed()
        ### pybullet settings
        self.ifrender = render
        self.physicsClient = p.connect(p.GUI if self.ifrender else p.DIRECT)
        p.setAdditionalSearchPath(pybullet_data.getDataPath())
        ### env variables
        self.robot_model = robot_model
        self.max_steps = max_steps
        self.num_foods = num_foods
        self.num_fakes = num_fakes
        self.object_size = object_size
        self.object_radius_scale = object_radius_scale
        self.object_radius_offset = object_radius_offset
        self.object_angle_scale = object_angle_scale
        self.plane_id = None
        self.robot = None
        self.object_ids = []
        ### episode variables
        self.steps = 0
        self.episode_rewards = 0.0

    def close(self):
        """Close environment.
        """
        p.disconnect(self.physicsClient)

    def reset(self):
        """Reset environment.
        """
        self.steps = 0
        self.episode_rewards = 0
        p.resetSimulation()
        # p.setTimeStep(1.0 / 240.0)
        p.setGravity(0, 0, self.GRAVITY)
        self.plane_id = p.loadURDF('plane.urdf')
        self.robot = self.robot_model()
        self.object_ids = []
        for i, (pos, orn) in enumerate(self._generateObjectPositions(num=(self.num_foods+self.num_fakes), radius_scale=self.object_radius_scale, radius_offset=self.object_radius_offset, angle_scale=self.object_angle_scale)):
            if i < self.num_foods:
                urdfPath = 'food_sphere.urdf'
            else:
                urdfPath = 'food_cube.urdf'
            object_id = p.loadURDF(urdfPath, pos, orn, globalScaling=self.object_size)
            self.object_ids.append(object_id)
        for i in range(self.BULLET_STEPS):
            p.stepSimulation()
        obs = self._getObservation()
        #print('reset laile')
        #self.robot.printAllJointInfo()
        return obs

    def step(self, action):
        """Apply action to environment, then return observation and reward.
        """
        self.steps += 1
        self.robot.setAction(action)
        reward = -1.0 * float(self.num_foods) / float(self.max_steps) # so agent needs to eat foods quickly
        for i in range(self.BULLET_STEPS):
            p.stepSimulation()
            reward += self._getReward()
        self.episode_rewards += reward
        obs = self._getObservation()
        done = self._isDone()
        pos, orn = self.robot.getPositionAndOrientation()
        info = { 'steps': self.steps, 'pos': pos, 'orn': orn }
        if done:
            #print('Done laile')
            info['episode'] = { 'r': self.episode_rewards, 'l': self.steps }
            # print(self.episode_rewards, self.steps)
        #print(self.robot.getBaseRollPosition(), self.robot.getTorsoLiftPosition(), self.robot.getHeadPosition(), self.robot.getArmPosition(), self.robot.getWristPosition(), self.robot.getGripperPosition()) # for HSR debug
        #print(self.robot.getHeadPosition(), self.robot.getGripperPosition()) # for R2D2 debug
        return obs, reward, done, info

    def render(self, mode='human', close=False):
        """This is a dummy function. This environment cannot control rendering timing.
        """
        if mode != 'rgb_array':
          return np.array([])
        return self._getObservation()

    def seed(self, seed=None):
        """Set random seed.
        """
        self.np_random, seed = seeding.np_random(seed)
        return [seed]

    def _getReward(self):
        """Detect contact points and return reward.
        """
        reward = 0
        contacted_object_ids = [ object_id for object_id in self.object_ids if self.robot.isContact(object_id) ]
        for object_id in contacted_object_ids:
            reward += 1 if self._isFood(object_id) else -1
            p.removeBody(object_id)
            self.object_ids.remove(object_id)
        return reward

    def _getObservation(self):
        """Get observation.
        """
        obs = self.robot.getObservation()
        return obs

    def _isFood(self, object_id):
        """Check if object_id is a food.
        """
        baseLink, urdfPath = p.getBodyInfo(object_id)
        return urdfPath == b'food_sphere.urdf' # otherwise, fake

    def _isDone(self):
        """Check if episode is done.
        """
        #print(self.object_ids,'self')
        available_object_ids = [ object_id for object_id in self.object_ids if self._isFood(object_id) ]
        #print(available_object_ids)
        return self.steps >= self.max_steps or len(available_object_ids) <= 0

    def _generateObjectPositions(self, num=1, retry=100, radius_scale=1.0, radius_offset=1.0, angle_scale=1.0, angle_offset=0.5*np.pi, z=1.5, near_distance=0.5):
        """Generate food positions randomly.
        """
        def genPos():
            r = radius_scale * self.np_random.rand() + radius_offset
            a = -np.pi * angle_scale + angle_offset
            b =  np.pi * angle_scale + angle_offset
            ang = (b - a) * self.np_random.rand() + a
            return np.array([r * np.sin(ang), r * np.cos(ang), z])
        def isNear(pos, poss):
            for p, o in poss:
                if np.linalg.norm(p - pos) < near_distance:
                    return True
            return False
        def genPosRetry(poss):
            for i in range(retry):
                pos = genPos()
                if not isNear(pos, poss):
                    return pos
            return genPos()
        poss = []
        for i in range(num):
            pos = genPosRetry(poss)
            orn = p.getQuaternionFromEuler([0.0, 0.0, 2.0*np.pi*self.np_random.rand()])
            poss.append((pos, orn))
        return poss
```

**Comment by Miffyli** [comment]
Much like araffin pointed out, there is little we can offer here as we do not have time to offer custom tech support per person, especially when the example code seems to work out as expected (the colab araffin linked). My recommendation is that you take a code that is known to work (e.g. the colab one), and modify it bit-by-bit until you hit a roadblock. The simplest starting point probably is to take the colab code and replace the env with yours.

Closing as no tech support.

**Comment by kevin-thankyou-lin** [comment]
Hey @JimLiu1213, I had the same issue and, for me, it was because

```
class VecVideoRecorder(VecEnvWrapper):
    """
    Wraps a VecEnv or VecEnvWrapper object to record rendered image as mp4 video.
    It requires ffmpeg or avconv to be installed on the machine.

    :param venv:
    :param video_folder: Where to save videos
    :param record_video_trigger: Function that defines when to start recording.
                                        The function takes the current number of step,
                                        and returns whether we should start recording or not.
    :param video_length:  Length of recorded videos
    :param name_prefix: Prefix to the video name
    """

    def __init__(
        self,
        venv: VecEnv,
        video_folder: str,
        record_video_trigger: Callable[[int], bool],
        video_length: int = 200,
        name_prefix: str = "rl-video",
    ):

        VecEnvWrapper.__init__(self, venv)

        self.env = venv
        # Temp variable to retrieve metadata
        temp_env = venv

        # Unwrap to retrieve metadata dict
        # that will be used by gym recorder
        while isinstance(temp_env, VecEnvWrapper):
            temp_env = temp_env.venv

        # if isinstance(temp_env, DummyVecEnv) or isinstance(temp_env, SubprocVecEnv):
        #     metadata = temp_env.get_attr("metadata")[0]
        # else:
        #     metadata = temp_env.metadata
        metadata = temp_env.metadata
```

the if statement in `stable_baselines3/common/vec_env/vec_video_recorder.py` 'discarded' my env's metadata. 

My fix was to comment out the get_attr in the if statement, so that metadata remained as `{'render.modes': ['human', 'rgb_array']}` and not `{'render.modes': []}`:

```
        # if isinstance(temp_env, DummyVecEnv) or isinstance(temp_env, SubprocVecEnv):
        #     metadata = temp_env.get_attr("metadata")[0]
        # else:
        #     metadata = temp_env.metadata
        metadata = temp_env.metadata
```

Also, I had to update my gym version to a higher version than 0.18.0 (0.19.0 works for me) because the ImageEncoder wasn't saving the frame properly (though I might've deleted something on accident).
