### ISSUE TITLE
[Bug?] `RuntimeError: File size unexpectedly exceeded ZIP64 limit` and switching from np.save to np.savez 

### ISSUE THREAD

**Issue by jkterry1** [DLR-RM/stable-baselines3#812]
So I'm using python 3.7, numpy 1.19.5 (the latest version of numpy that supports 3.7). I was training with roughly 4GB MLP models and automatically save them after training, and the runs crashed with `RuntimeError: File size unexpectedly exceeded ZIP64 limit`. Upon Googling this error, this is just something that happens in NumPy with matrices larger than 2GB (see https://github.com/numpy/numpy/issues/13153), which is a reasonable thing to support in SB3. While this sure feels like something numpy should fix after looking into the mechanisms of the bug, the official numpy maintainer recommendation was to switch from `.save` to `.savez`, and I'm aware of no new changes to this.

**Comment by jkterry1** [comment]
Full traceback:


```
[W 2022-03-07 23:57:46,869] Trial 6 failed because of the following error: RuntimeError('File size unexpectedly exceeded ZIP64 limit')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "/home/jkterry0/rl-baselines3-zoo/utils/exp_manager.py", line 685, in objective
    model.learn(self.n_timesteps, callback=eval_callback)
  File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/ppo/ppo.py", line 308, in learn
    reset_num_timesteps=reset_num_timesteps,
  File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 234, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 181, in collect_rollouts
    if callback.on_step() is False:
  File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/callbacks.py", line 88, in on_step
    return self._on_step()
  File "/home/jkterry0/rl-baselines3-zoo/utils/callbacks.py", line 48, in _on_step
    super(TrialEvalCallback, self)._on_step()
  File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/callbacks.py", line 421, in _on_step
    self.model.save(os.path.join(self.best_model_save_path, "best_model"))
  File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/base_class.py", line 775, in save
    save_to_zip_file(path, data=data, params=params_to_save, pytorch_variables=pytorch_variables)
  File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/save_util.py", line 322, in save_to_zip_file
    th.save(dict_, param_file)
  File "/opt/conda/lib/python3.7/zipfile.py", line 1161, in close
    'File size unexpectedly exceeded ZIP64 limit')
RuntimeError: File size unexpectedly exceeded ZIP64 limit
```

**Comment by Miffyli** [comment]
Related issue #759

Yup this is a known limitation, and I wonder if we should add the solution of #759 to the codebase. Need to check if this causes problems with older models (e.g. can you still load them up).

**Comment by jkterry1** [comment]
I did some additional testing, and at least my proposed solution is inadequate above 4GB:

```
import numpy as np
np.savez('hoge.npz', {'a': np.random.rand(2024, 2024, 256)})
```

Gives 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in savez
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 616, in savez
    _savez(file, args, kwds, False)
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 723, in _savez
    pickle_kwargs=pickle_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/format.py", line 664, in write_array
    pickle.dump(array, fp, protocol=3, **pickle_kwargs)
OverflowError: cannot serialize a bytes object larger than 4 GiB
```

**Comment by Miffyli** [comment]
Ah, right, only now I read the link you shared from numpy side. Try the `force_zip64` thing of #759 . That seems to do the trick, and if so, we could add it to master :)

**Comment by araffin** [comment]
I tried harder and could not reproduce the issue, even with 220 layers and a 4.3 GB zip... so now I'm really curious to know how you managed.

```python
from stable_baselines3 import SAC

model = SAC(
    "MlpPolicy",
    "Pendulum-v1",
    policy_kwargs=dict(
        net_arch=
            dict(
                qf=[1024] * 220,
                pi=[1024] * 220,
            )
        
    ),
    seed=1,
)
model.save("test_big_sac")
```


```
OS: Linux-5.4.0-104-generic-x86_64-with-debian-bullseye-sid #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022
Python: 3.7.9
Stable-Baselines3: 1.4.1a3
PyTorch: 1.11.0+cpu
GPU Enabled: False
Numpy: 1.20.3
Gym: 0.21.0
```

**Comment by ChipHennig** [comment]
So I have the exact same error trace because I used [CheckPointCallback](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/callbacks.py#L213).. could be the cause?

**Comment by Miffyli** [comment]
Quite likely the same issue. Try installing stable-baselines3 from the repository with `pip3 install git+https://github.com/DLR-RM/stable-baselines3`  (the change is not on pip yet, I think).

**Comment by ChipHennig** [comment]
Worked! Thanks
