### ISSUE TITLE
Got ‘RuntimeError: expected scalar type Float but found Double’ when using DDPG policy

### ISSUE THREAD

**Issue by MOYFbeta** [DLR-RM/stable-baselines3#853]
seems that it's due to some type error of the input tensor.

I got the error after a few rounds of successful forward call, then suddenly it throw errors below:

```
Traceback (most recent call last):
  File "c:\Users\zch\Documents\Unreal Projects\wurenji\main.py", line 52, in <module>
    model.learn(
  File "C:\ProgramData\Anaconda3\lib\site-packages\stable_baselines3\ddpg\ddpg.py", line 130, in learn
    return super(DDPG, self).learn(
  File "C:\ProgramData\Anaconda3\lib\site-packages\stable_baselines3\td3\td3.py", line 205, in learn
    return super(TD3, self).learn(
  File "C:\ProgramData\Anaconda3\lib\site-packages\stable_baselines3\common\off_policy_algorithm.py", line 373, in learn
    self.train(batch_size=self.batch_size, gradient_steps=gradient_steps)
  File "C:\ProgramData\Anaconda3\lib\site-packages\stable_baselines3\td3\td3.py", line 157, in train
    next_q_values = th.cat(self.critic_target(replay_data.next_observations, next_actions), dim=1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\stable_baselines3\common\policies.py", line 886, in forward
    return tuple(q_net(qvalue_input) for q_net in self.q_networks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\stable_baselines3\common\policies.py", line 886, in <genexpr>
    return tuple(q_net(qvalue_input) for q_net in self.q_networks)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Float but found Double
```

I modified 'commom/policy.py' class ContinuousCritic(BaseModel) at line 885 'forward(self, obs: th.Tensor, actions: th.Tensor) -> Tuple[th.Tensor, ...]:' by adding a .float() to convert input tensor to float and it works.

```python
    def forward(self, obs: th.Tensor, actions: th.Tensor) -> Tuple[th.Tensor, ...]:
        # Learn the features extractor using the policy loss only
        # when the features_extractor is shared with the actor
        with th.set_grad_enabled(not self.share_features_extractor):
            features = self.extract_features(obs)
        qvalue_input = th.cat([features, actions], dim=1).float() #here
        return tuple(q_net(qvalue_input) for q_net in self.q_networks)
```

**Comment by MOYFbeta** [comment]
my problem actually.

when defining action_space i used python's float instead of np.float32

```python
self.action_space = gym.spaces.Box(0,1,(1,9), dtype=np.float32) #'float' was used before
```
