### ISSUE TITLE
[Bug] Can't use as base policy a policy that is derivative of an existing policy

### ISSUE THREAD

**Issue by PartiallyTyped** [DLR-RM/stable-baselines3#88]
**Describe the bug**
A derived policy can't be used as the base policy for another algorithm.
Use case:

Derivative algorithm that expects a specific kind of policy.

**Code example**
```python
from typing import List, Tuple, Type, Union, Callable, Optional, Dict, Any
import numpy as np
import torch as th
import torch.nn.functional as F
from stable_baselines3.common import logger
from stable_baselines3.common.off_policy_algorithm import OffPolicyAlgorithm
from stable_baselines3.common.type_aliases import GymEnv, MaybeCallback
from stable_baselines3.common.utils import get_linear_fn
from stable_baselines3.dqn import DQN
from stable_baselines3.common.policies import register_policy
from stable_baselines3.dqn.policies import DQNPolicy

class SpecialDQNPolicy(DQNPolicy):
    def __init__(*vargs, **kwargs):
        super().__init__(*vargs, **kwargs)

SpecialMlpPolicy = SpecialDQNPolicy
register_policy("SpecialMlpPolicy", SpecialMlpPolicy)


class SpecialDQN(DQN):
    def __init__(self, policy: Union[str, Type[SpecialDQNPolicy]],
                 env: Union[GymEnv, str],
                 learning_rate: Union[float, Callable] = 1e-4,
                 buffer_size: int = 1000000,
                 learning_starts: int = 50000,
                 batch_size: Optional[int] = 32,
                 tau: float = 1.0,
                 gamma: float = 0.99,
                 train_freq: int = 4,
                 gradient_steps: int = 1,
                 n_episodes_rollout: int = -1,
                 optimize_memory_usage: bool = False,
                 target_update_interval: int = 10000,
                 exploration_fraction: float = 0.1,
                 exploration_initial_eps: float = 1.0,
                 exploration_final_eps: float = 0.05,
                 max_grad_norm: float = 10,
                 tensorboard_log: Optional[str] = None,
                 create_eval_env: bool = False,
                 policy_kwargs: Optional[Dict[str, Any]] = None,
                 verbose: int = 0,
                 seed: Optional[int] = None,
                 device: Union[th.device, str] = 'auto',
                 _init_setup_model: bool = True):
        super(DQN, self).__init__(policy, env, SpecialDQNPolicy, learning_rate,
                                  buffer_size, learning_starts, batch_size,
                                  tau, gamma, train_freq, gradient_steps,
                                  n_episodes_rollout, action_noise=None,  # No action noise
                                  policy_kwargs=policy_kwargs,
                                  tensorboard_log=tensorboard_log,
                                  verbose=verbose, device=device,
                                  create_eval_env=create_eval_env,
                                  seed=seed, sde_support=False,
                                  optimize_memory_usage=optimize_memory_usage)
        self.exploration_initial_eps = exploration_initial_eps
        self.exploration_final_eps = exploration_final_eps
        self.exploration_fraction = exploration_fraction
        self.target_update_interval = target_update_interval
        self.max_grad_norm = max_grad_norm
        # "epsilon" for the epsilon-greedy exploration
        self.exploration_rate = 0.0
        # Linear schedule will be defined in `_setup_model()`
        self.exploration_schedule = None
        self.q_net, self.q_net_target = None, None
        if _init_setup_model:
            self._setup_model()


```
Error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 35, in __init__
  File "/Users/steliostymvios/Projects/stable-baselines3/stable_baselines3/common/off_policy_algorithm.py", line 100, in __init__
    seed=seed, use_sde=use_sde, sde_sample_freq=sde_sample_freq)
  File "/Users/steliostymvios/Projects/stable-baselines3/stable_baselines3/common/base_class.py", line 70, in __init__
    self.policy_class = get_policy_from_name(policy_base, policy)
  File "/Users/steliostymvios/Projects/stable-baselines3/stable_baselines3/common/policies.py", line 653, in get_policy_from_name
    print(_policy_registry[base_policy_type])
KeyError: <class '__main__.SpecialDQNPolicy'>
```

The registry isn't filled correctly
```
>>> pprint(_policy_registry)
{<class 'stable_baselines3.common.policies.ActorCriticPolicy'>: {'CnnPolicy': <class 'stable_baselines3.common.policies.ActorCriticCnnPolicy'>,
                                                                 'MlpPolicy': <class 'stable_baselines3.common.policies.ActorCriticPolicy'>},
 <class 'stable_baselines3.sac.policies.SACPolicy'>: {'CnnPolicy': <class 'stable_baselines3.sac.policies.CnnPolicy'>,
                                                      'MlpPolicy': <class 'stable_baselines3.sac.policies.SACPolicy'>},
 <class 'stable_baselines3.td3.policies.TD3Policy'>: {'CnnPolicy': <class 'stable_baselines3.td3.policies.CnnPolicy'>,
                                                      'MlpPolicy': <class 'stable_baselines3.td3.policies.TD3Policy'>},
 <class 'stable_baselines3.dqn.policies.DQNPolicy'>: {'CnnPolicy': <class 'stable_baselines3.dqn.policies.CnnPolicy'>,
                                                      'MlpPolicy': <class 'stable_baselines3.dqn.policies.DQNPolicy'>,
                                                      'SpecialCnnPolicy': <class '__main__.SpecialCnnPolicy'>,
                                                      'SpecialMlpPolicy': <class '__main__.SpecialDQNPolicy'>}}
```

**Comment by Miffyli** [comment]
This is by design, because those policies can not be used with other algorithms. Those functions were designed to be used by vanilla stable-baselines3 algorithms (to make it easy to run algorithms with simple `Algorithm('MlpPolicy'...)`), and with custom algorithms one should provide the policy class instead of a string.

**Comment by PartiallyTyped** [comment]
I see, I was under the impression it was possible to register custom policies.

**Comment by PartiallyTyped** [comment]
It can probably be adapted to work to allow custom/derivative algorithms to work the same way.

**Comment by araffin** [comment]
>I see, I was under the impression it was possible to register custom policies.

It is possible but you need to specify `DQNPolicy` as the base class, both in the algorithm for your custom policy.
(See what I'm doing for DDPG and TD3: #92 , although in that case, the two are almost identical)
