### ISSUE TITLE
[Question] Custom args for Custom Policy Network

### ISSUE THREAD

**Issue by Syzygianinfern0** [DLR-RM/stable-baselines3#906]
### Question

I am following [the docs](https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html#advanced-example) for having a custom Policy Network for the PPO algorithm. I want to pass new custom args to the `class CustomNetwork` in that code but I am unable to do it. 

<details><summary>Here is a sample of what I want to do</summary>

Diff of the below code, wrt to original code from docs: https://www.diffchecker.com/tRb3aKdt

```python
from typing import Callable, Dict, List, Optional, Tuple, Type, Union

import gym
import torch as th
from stable_baselines3 import PPO
from stable_baselines3.common.policies import ActorCriticPolicy
from torch import nn


class CustomNetwork(nn.Module):
    """
    Custom network for policy and value function.
    It receives as input the features extracted by the feature extractor.

    :param feature_dim: dimension of the features extracted with the features_extractor (e.g. features from a CNN)
    :param last_layer_dim_pi: (int) number of units for the last layer of the policy network
    :param last_layer_dim_vf: (int) number of units for the last layer of the value network
    """

    def __init__(
        self,
        feature_dim: int,
        last_layer_dim_pi: int = 64,
        last_layer_dim_vf: int = 64,
        custom_variable=None,
    ):
        super(CustomNetwork, self).__init__()

        # IMPORTANT:
        # Save output dimensions, used to create the distributions
        self.latent_dim_pi = last_layer_dim_pi
        self.latent_dim_vf = last_layer_dim_vf

        # Policy network
        self.policy_net = nn.Sequential(nn.Linear(feature_dim, last_layer_dim_pi), nn.ReLU())
        # Value network
        self.value_net = nn.Sequential(nn.Linear(feature_dim, last_layer_dim_vf), nn.ReLU())
        self.custom_variable = custom_variable

    def forward(self, features: th.Tensor) -> Tuple[th.Tensor, th.Tensor]:
        """
        :return: (th.Tensor, th.Tensor) latent_policy, latent_value of the specified network.
            If all layers are shared, then ``latent_policy == latent_value``
        """
        return self.policy_net(features), self.value_net(features)

    def forward_actor(self, features: th.Tensor) -> th.Tensor:
        return self.policy_net(features)

    def forward_critic(self, features: th.Tensor) -> th.Tensor:
        return self.value_net(features)


class CustomActorCriticPolicy(ActorCriticPolicy):
    def __init__(
        self,
        observation_space: gym.spaces.Space,
        action_space: gym.spaces.Space,
        lr_schedule: Callable[[float], float],
        net_arch: Optional[List[Union[int, Dict[str, List[int]]]]] = None,
        activation_fn: Type[nn.Module] = nn.Tanh,
        *args,
        **kwargs,
    ):
        super(CustomActorCriticPolicy, self).__init__(
            observation_space,
            action_space,
            lr_schedule,
            net_arch,
            activation_fn,
            # Pass remaining arguments to base class
            *args,
            **kwargs,
        )
        # Disable orthogonal initialization
        self.ortho_init = False
        self.custom_variable = kwargs.get("custom_variable")

    def _build_mlp_extractor(self) -> None:
        self.mlp_extractor = CustomNetwork(self.features_dim, custom_variable=self.custom_variable)


model = PPO(CustomActorCriticPolicy, "CartPole-v1", verbose=1, policy_kwargs={"custom_variable": 123})
model.learn(5000)
```

The full error
```
Traceback (most recent call last):
  File "custom_rl.py", line 83, in <module>
    model = PPO(CustomActorCriticPolicy, "CartPole-v1", verbose=1, policy_kwargs={"custom_variable": 123})
  File "<env-path>/python3.7/site-packages/stable_baselines3/ppo/ppo.py", line 156, in __init__
    self._setup_model()
  File "<env-path>/python3.7/site-packages/stable_baselines3/ppo/ppo.py", line 159, in _setup_model
    super(PPO, self)._setup_model()
  File "<env-path>/python3.7/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 125, in _setup_model
    **self.policy_kwargs  # pytype:disable=not-instantiable
  File "custom_rl.py", line 73, in __init__
    **kwargs,
TypeError: __init__() got an unexpected keyword argument 'custom_variable'
```

</details>

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
Hello,
you need to retrieve the custom argument and delete it before calling parent constructor:

```python
from typing import Callable, Dict, List, Optional, Tuple, Type, Union

import gym
import torch as th
from stable_baselines3 import PPO
from stable_baselines3.common.policies import ActorCriticPolicy
from torch import nn


class CustomNetwork(nn.Module):
    """
    Custom network for policy and value function.
    It receives as input the features extracted by the feature extractor.

    :param feature_dim: dimension of the features extracted with the features_extractor (e.g. features from a CNN)
    :param last_layer_dim_pi: (int) number of units for the last layer of the policy network
    :param last_layer_dim_vf: (int) number of units for the last layer of the value network
    """

    def __init__(
        self,
        feature_dim: int,
        last_layer_dim_pi: int = 64,
        last_layer_dim_vf: int = 64,
        custom_variable=None,
    ):
        super(CustomNetwork, self).__init__()

        # IMPORTANT:
        # Save output dimensions, used to create the distributions
        self.latent_dim_pi = last_layer_dim_pi
        self.latent_dim_vf = last_layer_dim_vf

        # Policy network
        self.policy_net = nn.Sequential(
            nn.Linear(feature_dim, last_layer_dim_pi), nn.ReLU()
        )
        # Value network
        self.value_net = nn.Sequential(
            nn.Linear(feature_dim, last_layer_dim_vf), nn.ReLU()
        )
        self.custom_variable = custom_variable

    def forward(self, features: th.Tensor) -> Tuple[th.Tensor, th.Tensor]:
        """
        :return: (th.Tensor, th.Tensor) latent_policy, latent_value of the specified network.
            If all layers are shared, then ``latent_policy == latent_value``
        """
        return self.policy_net(features), self.value_net(features)

    def forward_actor(self, features: th.Tensor) -> th.Tensor:
        return self.policy_net(features)

    def forward_critic(self, features: th.Tensor) -> th.Tensor:
        return self.value_net(features)


class CustomActorCriticPolicy(ActorCriticPolicy):
    def __init__(
        self,
        observation_space: gym.spaces.Space,
        action_space: gym.spaces.Space,
        lr_schedule: Callable[[float], float],
        net_arch: Optional[List[Union[int, Dict[str, List[int]]]]] = None,
        activation_fn: Type[nn.Module] = nn.Tanh,
        *args,
        **kwargs,
    ):
        self.custom_variable = kwargs.get("custom_variable")
        if "custom_variable" in kwargs:
            del kwargs["custom_variable"]

        super().__init__(
            observation_space,
            action_space,
            lr_schedule,
            net_arch,
            activation_fn,
            # Pass remaining arguments to base class
            *args,
            **kwargs,
        )
        # Disable orthogonal initialization
        self.ortho_init = False

    def _build_mlp_extractor(self) -> None:
        self.mlp_extractor = CustomNetwork(
            self.features_dim, custom_variable=self.custom_variable
        )


model = PPO(
    CustomActorCriticPolicy,
    "CartPole-v1",
    verbose=1,
    policy_kwargs={"custom_variable": 123},
)
model.learn(5000)

```

**Comment by Syzygianinfern0** [comment]
This works perfectly. Thanks!
