### ISSUE TITLE
DDPG algorithm doesn't work with non-1d action space (probably other algs too)

### ISSUE THREAD

**Issue by Pulverizer2020** [DLR-RM/stable-baselines3#970]
### 🤖 Custom Gym Environment

```python
import gym
import numpy as np
from gym.spaces import Box

class TestEnv(gym.Env):
    metadata = {"render.modes": ["console"]}

    def __init__(self,
                max_step: int = 1,
                ) -> None:

        super().__init__()

        self.cur_step = 0
        self.max_step = max_step


        self.action_space_shape = (5,5)
        self.action_space = Box(low=-1, high=1, shape=self.action_space_shape)

        # observation space is the polarity of all normal users
        self.observation_space_shape = (5,)
        self.observation_space = Box(low=-1, high=1, shape=self.observation_space_shape)
        # self.init_obs = self.observation_space.sample()

        # self.good_counter = 0
        
        self.reset()

        return None

    def render(self, mode="console"):
        pass

    def close(self):
        pass

    def reset(self) -> np.array:
        self.cur_step = 0
        return self.observation_space.sample()

    def step(self, action: np.array):
        observation = np.array(action[0])

        self.cur_step += 1
        done = self.cur_step >= self.max_step
        info = {"info": None}
        
        reward = np.sum(action[0])

        return observation, reward, done, info

```

### Describe the bug

I expected DDPG to successfully train and return. For example, a simple example like this but using a 1d action space shape [ex: shape=np.array([25,]) works perfectly]. However, it seems like the necessary internal array reshapes haven't been implemented.

### Code example

Run this code with the above custom environment, and the error should be encountered

```python
if __name__ == "__main__":
    from stable_baselines3 import DDPG
    
    env = TestEnv(max_step=5)

    model = DDPG("MlpPolicy", env, verbose=1)
    model.learn(total_timesteps=1000, log_interval=10)
```

Here is the error and its accompanying stackframe:

```bash
Traceback (most recent call last):
  File "[FILE NAME REDACTED]", line 60, in <module>
    model.learn(total_timesteps=1000, log_interval=10)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/stable_baselines3/ddpg/ddpg.py", line 130, in learn
    return super().learn(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/stable_baselines3/td3/td3.py", line 211, in learn
    return super().learn(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 346, in learn
    rollout = self.collect_rollouts(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 595, in collect_rollouts
    self._store_transition(replay_buffer, buffer_actions, new_obs, rewards, dones, infos)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 507, in _store_transition
    replay_buffer.add(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/stable_baselines3/common/buffers.py", line 268, in add
    self.actions[self.pos] = np.array(action).copy()
ValueError: could not broadcast input array from shape (5,5) into shape (1,25)

```

### System Info
Describe the characteristic of your environment:
downloaded using pip
OS: macOS-12.2.1-arm64-arm-64bit Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
Python: 3.10.2
Stable-Baselines3: 1.6.0
PyTorch: 1.11.0
GPU Enabled: False
Numpy: 1.22.3
Gym: 0.25.0

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have checked my env using the env checker (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by qgallouedec** [comment]
It seems like a bug.

I'm having trouble understanding all the principles of broadcasting with numpy. So I wonder why not always reshape the action (and the observation) to the appropriate dimension instead of assuming that the broadcast will work? I submit  #971 to continue the discussion about this fix.
