### ISSUE TITLE
Compatibility issue with Torch 1.7

### ISSUE THREAD

**Issue by anilkurkcu** [DLR-RM/stable-baselines3#976]
I am getting this error:

import gym
from stable_baselines3 import A2C
env = gym.make('CartPole-v1')
model = A2C('MlpPolicy', env, verbose=1, device='cuda:7')
model.learn(total_timesteps=10000)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kurkcua/miniconda3/envs/venv4/lib/python3.8/site-packages/stable_baselines3/a2c/a2c.py", line 197, in learn
    return super().learn(
  File "/home/kurkcua/miniconda3/envs/venv4/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 247, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "/home/kurkcua/miniconda3/envs/venv4/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 166, in collect_rollouts
    actions, values, log_probs = self.policy(obs_tensor)
  File "/home/kurkcua/miniconda3/envs/venv4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kurkcua/miniconda3/envs/venv4/lib/python3.8/site-packages/stable_baselines3/common/policies.py", line 589, in forward
    latent_pi, latent_vf = self.mlp_extractor(features)
  File "/home/kurkcua/miniconda3/envs/venv4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kurkcua/miniconda3/envs/venv4/lib/python3.8/site-packages/stable_baselines3/common/torch_layers.py", line 230, in forward
    return self.policy_net(shared_latent), self.value_net(shared_latent)
  File "/home/kurkcua/miniconda3/envs/venv4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kurkcua/miniconda3/envs/venv4/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/kurkcua/miniconda3/envs/venv4/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kurkcua/miniconda3/envs/venv4/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/kurkcua/miniconda3/envs/venv4/lib/python3.8/site-packages/torch/nn/functional.py", line 1690, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

System info:

>>> torch.version.cuda
'10.1'
>>> torch.__version__
'1.7.1'
>>> sb3.get_system_info()
OS: Linux-4.15.0-76-generic-x86_64-with-glibc2.17 #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020
Python: 3.8.13
Stable-Baselines3: 1.6.0
PyTorch: 1.7.1
GPU Enabled: True
Numpy: 1.22.3
Gym: 0.21.0

({'OS': 'Linux-4.15.0-76-generic-x86_64-with-glibc2.17 #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020', 'Python': '3.8.13', 'Stable-Baselines3': '1.6.0', 'PyTorch': '1.7.1', 'GPU Enabled': 'True', 'Numpy': '1.22.3', 'Gym': '0.21.0'}, 'OS: Linux-4.15.0-76-generic-x86_64-with-glibc2.17 #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020\nPython: 3.8.13\nStable-Baselines3: 1.6.0\nPyTorch: 1.7.1\nGPU Enabled: True\nNumpy: 1.22.3\nGym: 0.21.0\n')

GPU info: 8 x 'Tesla V100-SXM2-32GB-LS'

Everything is working fine in cpu-only mode.

**Comment by anilkurkcu** [comment]
Thank you for your reply. I had to switch the CUDA toolkit from version 10.1 to version 11. Everything is working smoothly now.
