### ISSUE TITLE
[Bug] can't make_vec_env with highway-env

### ISSUE THREAD

**Issue by KexianShen** [DLR-RM/stable-baselines3#993]
### 🐛 Bug

make_vec_env failed to create vectorized envs with env_id being an environment class, because of env wrappers.
 

### To Reproduce

```python
import gym
import highway_env

from stable_baselines3.common.env_util import make_vec_env

env = gym.make("highway-fast-v0")
env = make_vec_env(env, n_envs=1, seed=0)#, vec_env_cls = SubprocVecEnv)
```

```bash
Traceback (most recent call last):
  File "/home/kexian/Desktop/mac/pilot-env/highway_vec_env.py", line 8, in <module>
    env = make_vec_env(env, n_envs=1, seed=0)
  File "/home/kexian/repo/stable-baselines3/stable_baselines3/common/env_util.py", line 105, in make_vec_env
    return vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
  File "/home/kexian/repo/stable-baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 25, in __init__
    self.envs = [fn() for fn in env_fns]
  File "/home/kexian/repo/stable-baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 25, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "/home/kexian/repo/stable-baselines3/stable_baselines3/common/env_util.py", line 82, in _init
    env = env_id(**env_kwargs)
TypeError: 'OrderEnforcing' object is not callable
```

also with CartPole-v1

```python
import gym

from stable_baselines3.common.env_util import make_vec_env

env = gym.make("CartPole-v1")
env = make_vec_env(env, n_envs=1, seed=0)
```

```bash
Traceback (most recent call last):
  File "/home/kexian/Desktop/mac/pilot-env/highway_vec_env.py", line 8, in <module>
    env = make_vec_env(env, n_envs=1, seed=0)
  File "/home/kexian/repo/stable-baselines3/stable_baselines3/common/env_util.py", line 105, in make_vec_env
    return vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
  File "/home/kexian/repo/stable-baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 25, in __init__
    self.envs = [fn() for fn in env_fns]
  File "/home/kexian/repo/stable-baselines3/stable_baselines3/common/vec_env/dummy_vec_env.py", line 25, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "/home/kexian/repo/stable-baselines3/stable_baselines3/common/env_util.py", line 82, in _init
    env = env_id(**env_kwargs)
TypeError: 'TimeLimit' object is not callable
```

### System Info

OS: Linux-5.15.0-41-generic-x86_64-with-glibc2.31 #44~20.04.1-Ubuntu SMP Fri Jun 24 13:27:29 UTC 2022
Python: 3.9.7
Stable-Baselines3: 1.6.0
PyTorch: 1.11.0
GPU Enabled: True
Numpy: 1.21.0
Gym: 0.21.0/0.25.0 both failed

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)
- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by araffin** [comment]
Hello,
please take a close look at the examples on the doc and/or at the parameters description of `make_vec_env`.
You must pass an env id (str) or a callable/class, not an env object.

**Comment by KexianShen** [comment]
OK, got it. The [example in doc](https://stable-baselines3.readthedocs.io/en/master/guide/examples.html#id5) works fine. But the following script throws errors.
```python
env = make_vec_env("CartPole-v1", n_envs=2, seed=0, vec_env_cls=SubprocVecEnv)
```
```bash
Traceback (most recent call last):
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/multiprocessing/forkserver.py", line 274, in main
    code = _serve_one(child_r, fds,
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/multiprocessing/forkserver.py", line 313, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kexian/Desktop/mac/pilot-env/highway_vec_env.py", line 33, in <module>
    env = make_vec_env("CartPole-v1", n_envs=2, seed=0, vec_env_cls=SubprocVecEnv)
  File "/home/kexian/repo/stable-baselines3/stable_baselines3/common/env_util.py", line 105, in make_vec_env
    return vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
  File "/home/kexian/repo/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", line 106, in __init__
    process.start()
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/multiprocessing/popen_forkserver.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/home/kexian/Desktop/mac/pilot-env/highway_vec_env.py", line 33, in <module>
    env = make_vec_env("CartPole-v1", n_envs=2, seed=0, vec_env_cls=SubprocVecEnv)
  File "/home/kexian/repo/stable-baselines3/stable_baselines3/common/env_util.py", line 105, in make_vec_env
    return vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
  File "/home/kexian/repo/stable-baselines3/stable_baselines3/common/vec_env/subproc_vec_env.py", line 111, in __init__
    observation_space, action_space = self.remotes[0].recv()
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/kexian/app/miniconda3/envs/rl/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by qgallouedec** [comment]
As the error suggests try

```python 
if __name__ == "__main__":
    env = make_vec_env("CartPole-v1", n_envs=2, seed=0, vec_env_cls=SubprocVecEnv)
```

**Comment by KexianShen** [comment]
Thanks for a quick reply.
